# Generated by makeguitarmigrations command! [DIGEST:b6b0c3a1208a8d30d26e103127ef7979]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossapp_retire_owner', '0001_initial'),
        ('crossapp_retire_child', '0001_initial'),
    ]

    operations = [
        # MTI Soft Delete Rule on "crossapp_retire_child_heir" table (parent "crossapp_retire_owner_retiree")! [SQL:a3eecc2b0c00]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "crossapp_retire_child_heir"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "crossapp_retire_owner_retiree"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."retiree_ptr_id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "crossapp_retire_child_heir";
        """,
        ),

        # Soft Delete Rule on "crossapp_retire_child_dependant" table! [SQL:858111121c9a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "crossapp_retire_child_dependant"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "crossapp_retire_child_dependant"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "crossapp_retire_child_dependant";
        """,
        ),

        # Soft Delete Related Rule on "crossapp_retire_child_dependant" that is related to "crossapp_retire_owner_retiree"! [SQL:4cb6e050bf13]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_crossapp_retire_child_dependant"
                AS ON UPDATE TO "crossapp_retire_owner_retiree"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "crossapp_retire_child_dependant"
                    SET _deleted_at = NOW()
                    WHERE "heir_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_crossapp_retire_child_dependant" ON "crossapp_retire_owner_retiree";
        """,
        ),

    ]
