# Generated by Django 5.2.15 on 2026-09-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossapp_retire_child', '0003_alter_dependant_heir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='heir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='crossapp_retire_child.heir'),
        ),
    ]
