# Generated by makeguitarmigrations command! [DIGEST:f36893017e0a72e2fb2ea871265abadd]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossapp_retire_owner', '0003_auto_enforcement'),
        ('crossapp_retire_owner', '0001_initial'),
        ('crossapp_retire_child', '0004_alter_dependant_heir'),
    ]

    operations = [
        # Soft Delete Related Rule on "crossapp_retire_child_dependant" that is related to "crossapp_retire_owner_retiree"! [SQL:4cb6e050bf13]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_crossapp_retire_child_dependant"
                AS ON UPDATE TO "crossapp_retire_owner_retiree"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "crossapp_retire_child_dependant"
                    SET _deleted_at = NOW()
                    WHERE "heir_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_crossapp_retire_child_dependant" ON "crossapp_retire_owner_retiree";
        """,
        ),

    ]
