"""Tests for the ``makemigrations`` override that also runs guitar generation.

All six tests here used to mock both the real ``makemigrations`` ``handle`` and the
module's own ``call_command``, asserting only on call arguments -- every one of them would
still pass if ``makeguitarmigrations`` became a same-named no-op, since nothing checked
that a migration file actually appeared. These run the real command against a real
throwaway app instead (``tests/makemigrations_override/``, no migrations checked in at
all), and assert on what actually landed on disk.
"""

from __future__ import annotations

from io import StringIO
from pathlib import Path

import pytest
from django.apps import apps
from django.core.management import call_command
from django.test import override_settings


APP_LABEL = 'makemigrations_override'
_ENFORCEMENT_MARKER = 'Generated by makeguitarmigrations command!'


def _migrations_dir() -> Path:
    return Path(apps.get_app_config(APP_LABEL).path) / 'migrations'


def _generated_files() -> set[Path]:
    return {path for path in _migrations_dir().glob('*.py') if path.name != '__init__.py'}


@pytest.fixture
def _clean_migrations():
    """Removes whatever a test generates, even if an assertion fails first."""
    before = _generated_files()
    yield
    for path in _generated_files() - before:
        path.unlink()


_scoped = override_settings(LOCAL_APPS=['tests.testapp', 'tests.makemigrations_override'])


@pytest.mark.django_db
@_scoped
def test_makemigrations_writes_both_schema_and_enforcement_migrations_for_real(
    _clean_migrations,
):
    call_command('makemigrations', APP_LABEL, stdout=StringIO())

    files = _generated_files()
    assert len(files) == 2, files
    enforcement = [f for f in files if _ENFORCEMENT_MARKER in f.read_text()]
    schema = [f for f in files if f not in enforcement]
    assert len(enforcement) == 1, files
    assert len(schema) == 1, files
    assert 'CreateModel' in schema[0].read_text()
    assert 'makemigrations_override_probe' in enforcement[0].read_text()


@pytest.mark.django_db
@_scoped
def test_auto_make_migrations_false_writes_only_the_schema_migration(_clean_migrations):
    with override_settings(GUITARS_AUTO_MAKE_MIGRATIONS=False):
        call_command('makemigrations', APP_LABEL, stdout=StringIO())

    files = _generated_files()
    assert len(files) == 1, files
    assert 'CreateModel' in files.pop().read_text()


@pytest.mark.django_db
@_scoped
def test_check_reports_needed_changes_for_both_layers_and_writes_nothing(_clean_migrations):
    # Django's own --check exits via sys.exit(1) rather than raising CommandError.
    with pytest.raises(SystemExit):
        call_command('makemigrations', APP_LABEL, '--check', stdout=StringIO(), stderr=StringIO())

    assert _generated_files() == set()


@pytest.mark.django_db
@_scoped
def test_dry_run_writes_nothing_for_either_layer(_clean_migrations):
    call_command('makemigrations', APP_LABEL, '--dry-run', stdout=StringIO())

    assert _generated_files() == set()


@pytest.mark.django_db
@_scoped
def test_empty_writes_only_the_scaffold_no_recursion(_clean_migrations):
    """``makeguitarmigrations`` scaffolds its own migrations via ``makemigrations
    --empty``, which re-enters this same override -- without the guard this loops
    forever. Proven for real: exactly one file appears, and the call returns at all."""
    call_command(
        'makemigrations', APP_LABEL, '--empty', '--name', 'probe_scaffold', stdout=StringIO()
    )

    files = _generated_files()
    assert len(files) == 1, files
    assert 'operations = [\n    ]' in files.pop().read_text()
