"""Tests for the ``makemigrations`` override that also runs guitar generation.

All six tests here used to mock both the real ``makemigrations`` ``handle`` and the
module's own ``call_command``, asserting only on call arguments -- every one of them would
still pass if ``makeguitarmigrations`` became a same-named no-op, since nothing checked
that a migration file actually appeared. These run the real command against a real
throwaway app instead (``tests/makemigrations_override/``, no migrations checked in at
all), and assert on what actually landed on disk.

The app is added to ``INSTALLED_APPS`` here, inside the ``_scoped_app`` fixture, rather
than in ``tests/settings.py`` -- it has no migrations checked in at all, and an app
installed that way trips the *unscoped* ``makemigrations --check`` CI runs regardless of
``LOCAL_APPS`` (Django's own schema check, not guitars' scoping, examines every installed
app). Scoping the installation to these tests keeps it invisible to everything else.

Every test here writes real files into ``tests/makemigrations_override/migrations/`` and
diffs the directory listing against a "before" snapshot -- so two of these tests dispatched
to different xdist workers at the same moment could see each other's files. ``pytestmark``
pins the whole module to one worker (the same fix ``TestPgbouncerTransactionPooling`` in
``test_concurrency.py`` uses for a differently-shaped shared resource); the scaffolding test
in ``test_tenancy_internals.py::TestScaffolding`` shares this app and carries the same
group name for the same reason.
"""

from __future__ import annotations

from io import StringIO
from pathlib import Path

import pytest
from django.apps import apps
from django.conf import settings as django_settings
from django.core.management import CommandError, call_command
from django.test import override_settings


pytestmark = pytest.mark.xdist_group(name='makemigrations_override_dir')

APP_LABEL = 'makemigrations_override'
_ENFORCEMENT_MARKER = 'Generated by makeguitarmigrations command!'


def _generated_files(migrations_dir: Path) -> set[Path]:
    return {path for path in migrations_dir.glob('*.py') if path.name != '__init__.py'}


@pytest.fixture
def _scoped_app():
    """Installs the throwaway app for one test's duration and cleans up what it wrote.

    ``override_settings`` runs as a context manager here, not a decorator, so its effect
    (and the app becoming resolvable via ``apps.get_app_config``) is active before this
    fixture -- and therefore the test body -- ever runs, and stays active through the
    generated-files cleanup below it.
    """
    with override_settings(
        INSTALLED_APPS=[*django_settings.INSTALLED_APPS, 'tests.makemigrations_override'],
        LOCAL_APPS=['tests.testapp', 'tests.makemigrations_override'],
    ):
        migrations_dir = Path(apps.get_app_config(APP_LABEL).path) / 'migrations'
        before = _generated_files(migrations_dir)
        yield migrations_dir
        for path in _generated_files(migrations_dir) - before:
            path.unlink()


@pytest.mark.django_db
def test_makemigrations_writes_both_schema_and_enforcement_migrations_for_real(_scoped_app):
    call_command('makemigrations', APP_LABEL, stdout=StringIO())

    files = _generated_files(_scoped_app)
    assert len(files) == 2, files
    enforcement = [f for f in files if _ENFORCEMENT_MARKER in f.read_text()]
    schema = [f for f in files if f not in enforcement]
    assert len(enforcement) == 1, files
    assert len(schema) == 1, files
    assert 'CreateModel' in schema[0].read_text()
    assert 'makemigrations_override_probe' in enforcement[0].read_text()


@pytest.mark.django_db
def test_auto_make_migrations_false_writes_only_the_schema_migration(_scoped_app):
    with override_settings(GUITARS_AUTO_MAKE_MIGRATIONS=False):
        call_command('makemigrations', APP_LABEL, stdout=StringIO())

    files = _generated_files(_scoped_app)
    assert len(files) == 1, files
    assert 'CreateModel' in files.pop().read_text()


@pytest.mark.django_db
def test_check_reports_needed_changes_for_both_layers_and_writes_nothing(_scoped_app):
    # Django's own --check exits via sys.exit(1) rather than raising CommandError.
    with pytest.raises(SystemExit):
        call_command('makemigrations', APP_LABEL, '--check', stdout=StringIO(), stderr=StringIO())

    assert _generated_files(_scoped_app) == set()


@pytest.mark.django_db
def test_check_reports_missing_enforcement_when_schema_is_already_current(_scoped_app):
    """The schema and enforcement layers are checked independently: the schema layer can
    already be up to date (nothing for Django's own --check to exit non-zero over) while
    the enforcement layer is still missing, and --check must still fail in that case.

    Regression test: step 2 used to gate on ``self.dry_run``, which Django's own handle()
    forces to ``True`` whenever --check is passed (check implies dry-run for the schema
    half) -- so this exact case exited 0 silently, printing "not checked because of
    --dry-run" without ever running the enforcement check.
    """
    with override_settings(GUITARS_AUTO_MAKE_MIGRATIONS=False):
        call_command('makemigrations', APP_LABEL, stdout=StringIO())

    written = _generated_files(_scoped_app)
    assert len(written) == 1, written

    out, err = StringIO(), StringIO()
    with pytest.raises(CommandError):
        call_command('makemigrations', APP_LABEL, '--check', stdout=out, stderr=err)

    assert 'not checked because of --dry-run' not in out.getvalue()
    # --check must never write, even though it found something missing.
    assert _generated_files(_scoped_app) == written


@pytest.mark.django_db
def test_dry_run_writes_nothing_for_either_layer(_scoped_app):
    out = StringIO()
    call_command('makemigrations', APP_LABEL, '--dry-run', stdout=out)

    assert _generated_files(_scoped_app) == set()
    assert 'Enforcement-migration status was not checked because of --dry-run.' in out.getvalue()


@pytest.mark.django_db
def test_empty_writes_only_the_scaffold_no_recursion(_scoped_app):
    """``makeguitarmigrations`` scaffolds its own migrations via ``makemigrations
    --empty``, which re-enters this same override -- without the guard this loops
    forever. Proven for real: exactly one file appears, and the call returns at all."""
    call_command(
        'makemigrations', APP_LABEL, '--empty', '--name', 'probe_scaffold', stdout=StringIO()
    )

    files = _generated_files(_scoped_app)
    assert len(files) == 1, files
    assert 'operations = [\n    ]' in files.pop().read_text()
