"""Tests for the ``makemigrations`` override that also runs guitar generation -- against a
real throwaway app, asserting on disk output, not mocked ``call_command``. ``pytestmark``
pins the module to one xdist worker since tests diff a real migrations-dir snapshot."""

from __future__ import annotations

from io import StringIO
from pathlib import Path

import pytest
from django.apps import apps
from django.conf import settings as django_settings
from django.core.management import CommandError, call_command
from django.test import override_settings


pytestmark = pytest.mark.xdist_group(name='makemigrations_override_dir')

APP_LABEL = 'makemigrations_override'
_ENFORCEMENT_MARKER = 'Generated by makeguitarmigrations command!'


def _generated_files(migrations_dir: Path) -> set[Path]:
    return {path for path in migrations_dir.glob('*.py') if path.name != '__init__.py'}


@pytest.fixture
def _scoped_app():
    """Installs the throwaway app for one test's duration and cleans up what it wrote.
    ``override_settings`` runs as a context manager, not a decorator, so it's active
    before this fixture (and the test body) runs, and through cleanup below it."""
    with override_settings(
        INSTALLED_APPS=[*django_settings.INSTALLED_APPS, 'tests.makemigrations_override'],
        LOCAL_APPS=['tests.testapp', 'tests.makemigrations_override'],
    ):
        migrations_dir = Path(apps.get_app_config(APP_LABEL).path) / 'migrations'
        before = _generated_files(migrations_dir)
        yield migrations_dir
        for path in _generated_files(migrations_dir) - before:
            path.unlink()


@pytest.mark.django_db
def test_makemigrations_writes_both_schema_and_enforcement_migrations_for_real(_scoped_app):
    call_command('makemigrations', APP_LABEL, stdout=StringIO())

    files = _generated_files(_scoped_app)
    assert len(files) == 2, files
    enforcement = [f for f in files if _ENFORCEMENT_MARKER in f.read_text()]
    schema = [f for f in files if f not in enforcement]
    assert len(enforcement) == 1, files
    assert len(schema) == 1, files
    assert 'CreateModel' in schema[0].read_text()
    assert 'makemigrations_override_probe' in enforcement[0].read_text()


@pytest.mark.django_db
def test_auto_make_migrations_false_writes_only_the_schema_migration(_scoped_app):
    with override_settings(GUITARS_AUTO_MAKE_MIGRATIONS=False):
        call_command('makemigrations', APP_LABEL, stdout=StringIO())

    files = _generated_files(_scoped_app)
    assert len(files) == 1, files
    assert 'CreateModel' in files.pop().read_text()


@pytest.mark.django_db
def test_check_reports_needed_changes_for_both_layers_and_writes_nothing(_scoped_app):
    # Django's own --check exits via sys.exit(1) rather than raising CommandError.
    with pytest.raises(SystemExit):
        call_command('makemigrations', APP_LABEL, '--check', stdout=StringIO(), stderr=StringIO())

    assert _generated_files(_scoped_app) == set()


@pytest.mark.django_db
def test_check_reports_missing_enforcement_when_schema_is_already_current(_scoped_app):
    """Schema and enforcement check independently: schema can be current while enforcement
    is missing, and --check must still fail. Regression: step 2 used to gate on
    ``self.dry_run``, forced True by Django's handle() under --check, so this silently exited 0."""
    with override_settings(GUITARS_AUTO_MAKE_MIGRATIONS=False):
        call_command('makemigrations', APP_LABEL, stdout=StringIO())

    written = _generated_files(_scoped_app)
    assert len(written) == 1, written

    out, err = StringIO(), StringIO()
    with pytest.raises(CommandError):
        call_command('makemigrations', APP_LABEL, '--check', stdout=out, stderr=err)

    assert 'not checked because of --dry-run' not in out.getvalue()
    # --check must never write, even though it found something missing.
    assert _generated_files(_scoped_app) == written


@pytest.mark.django_db
def test_dry_run_writes_nothing_for_either_layer(_scoped_app):
    out = StringIO()
    call_command('makemigrations', APP_LABEL, '--dry-run', stdout=out)

    assert _generated_files(_scoped_app) == set()
    assert 'Enforcement-migration status was not checked because of --dry-run.' in out.getvalue()


@pytest.mark.django_db
def test_empty_writes_only_the_scaffold_no_recursion(_scoped_app):
    """``makeguitarmigrations`` scaffolds its own migrations via ``makemigrations
    --empty``, which re-enters this same override -- without the guard this loops
    forever. Proven for real: exactly one file appears, and the call returns at all."""
    call_command(
        'makemigrations', APP_LABEL, '--empty', '--name', 'probe_scaffold', stdout=StringIO()
    )

    files = _generated_files(_scoped_app)
    assert len(files) == 1, files
    assert 'operations = [\n    ]' in files.pop().read_text()


def test_the_xdist_group_mark_is_actually_honoured(pytestconfig):
    """``xdist_group`` is a no-op under xdist's default ``--dist load``, and both modules
    writing to this app's migrations dir rely on it to stay on one worker -- without it a
    teardown here unlinks a file the other module's ``makemigrations`` is mid-import of."""
    # Read from the ini, not ``getoption('dist')``: a worker reports ``no`` for that whatever
    # the controller was given, so the option would assert only in a serial run -- exactly the
    # run where nothing is distributed and the marks could not have mattered anyway.
    addopts = pytestconfig.getini('addopts')
    mode = addopts[addopts.index('--dist') + 1] if '--dist' in addopts else None
    assert mode == 'loadgroup', (
        'pytest --dist must be loadgroup (set in pyproject.toml addopts) or the '
        'xdist_group marks pinning this module to one worker are silently ignored'
    )
