"""Every byte of raw SQL the kit emits, re-exported flat. **This module's public names
are a frozen interface** -- pre-1.1.0 migrations reference them by name and are already
applied in consuming projects. See ``docs/api-reference.md``'s frozen-names list."""

from .policy import (
    EXEMPT_POLICY_PREFIX,
    TENANT_POLICY,
    create_exempt_policy,
    create_table_rls,
    create_tenant_policy,
    disable_rls,
    drop_all_exempt_policies,
    drop_exempt_policy,
    drop_table_rls,
    drop_tenant_policy,
    enable_rls,
    force_rls,
    no_force_rls,
    replace_table_rls,
)
from .soft_delete import (
    CREATE_MTI_SOFT_DELETE_RULE,
    CREATE_SOFT_DELETE_RELATED_OBJECTS_RULE,
    CREATE_SOFT_DELETE_RELATED_OBJECTS_RULE_VIA,
    CREATE_SOFT_DELETE_RULE,
    DROP_MTI_SOFT_DELETE_RULE,
    DROP_SOFT_DELETE_RELATED_OBJECTS_RULE,
    DROP_SOFT_DELETE_RELATED_OBJECTS_RULE_VIA,
    DROP_SOFT_DELETE_RULE,
    SWITCH_OFF_HARD_DELETION,
    SWITCH_ON_HARD_DELETION,
)
from .triggers import (
    ADOPT_PARENT_UPDATED_AT_TRIGGER,
    ADOPT_UPDATED_AT_TRIGGER,
    CREATE_PARENT_UPDATED_AT_TRIGGER,
    CREATE_PARENT_UPDATED_AT_TRIGGER_FUNCTION,
    CREATE_UPDATED_AT_TRIGGER,
    CREATE_UPDATED_AT_TRIGGER_FUNCTION,
    DROP_PARENT_UPDATED_AT_TRIGGER,
    DROP_PARENT_UPDATED_AT_TRIGGER_FUNCTION,
    DROP_UPDATED_AT_TRIGGER,
    DROP_UPDATED_AT_TRIGGER_FUNCTION,
    REPLACE_PARENT_UPDATED_AT_TRIGGER,
    REPLACE_PARENT_UPDATED_AT_TRIGGER_FUNCTION,
    REPLACE_UPDATED_AT_TRIGGER,
    REPLACE_UPDATED_AT_TRIGGER_FUNCTION,
)


# One flat sorted list -- frozen names, so a reviewer diffing a release should see an
# insertion, never a reshuffle. tests/test_sql_interface.py compares the set.
__all__ = [
    'ADOPT_PARENT_UPDATED_AT_TRIGGER',
    'ADOPT_UPDATED_AT_TRIGGER',
    'CREATE_MTI_SOFT_DELETE_RULE',
    'CREATE_PARENT_UPDATED_AT_TRIGGER',
    'CREATE_PARENT_UPDATED_AT_TRIGGER_FUNCTION',
    'CREATE_SOFT_DELETE_RELATED_OBJECTS_RULE',
    'CREATE_SOFT_DELETE_RELATED_OBJECTS_RULE_VIA',
    'CREATE_SOFT_DELETE_RULE',
    'CREATE_UPDATED_AT_TRIGGER',
    'CREATE_UPDATED_AT_TRIGGER_FUNCTION',
    'DROP_MTI_SOFT_DELETE_RULE',
    'DROP_PARENT_UPDATED_AT_TRIGGER',
    'DROP_PARENT_UPDATED_AT_TRIGGER_FUNCTION',
    'DROP_SOFT_DELETE_RELATED_OBJECTS_RULE',
    'DROP_SOFT_DELETE_RELATED_OBJECTS_RULE_VIA',
    'DROP_SOFT_DELETE_RULE',
    'DROP_UPDATED_AT_TRIGGER',
    'DROP_UPDATED_AT_TRIGGER_FUNCTION',
    'EXEMPT_POLICY_PREFIX',
    'REPLACE_PARENT_UPDATED_AT_TRIGGER',
    'REPLACE_PARENT_UPDATED_AT_TRIGGER_FUNCTION',
    'REPLACE_UPDATED_AT_TRIGGER',
    'REPLACE_UPDATED_AT_TRIGGER_FUNCTION',
    'SWITCH_OFF_HARD_DELETION',
    'SWITCH_ON_HARD_DELETION',
    'TENANT_POLICY',
    'create_exempt_policy',
    'create_table_rls',
    'create_tenant_policy',
    'disable_rls',
    'drop_all_exempt_policies',
    'drop_exempt_policy',
    'drop_table_rls',
    'drop_tenant_policy',
    'enable_rls',
    'force_rls',
    'no_force_rls',
    'replace_table_rls',
]
