# Generated by Django 5.2.15 on 2026-08-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossapp_tenant_ancestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantedancestor',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='crossapp_tenant_ancestor.locallabel'),
            preserve_default=False,
        ),
    ]
