# Generated by makeguitarmigrations command! [DIGEST:1f80272c4b2c49eaa9eb4226a1de8958]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('crossapp_tenant_ancestor', '0002_tenantedancestor_label'),
    ]

    operations = [
        # Updated at Trigger on "crossapp_tenant_ancestor_locallabel" table! [SQL:b0ef4c65836e]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "crossapp_tenant_ancestor_locallabel" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "crossapp_tenant_ancestor_locallabel";
        """,
        ),

        # Soft Delete Rule on "crossapp_tenant_ancestor_locallabel" table! [SQL:5650008d2459]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "crossapp_tenant_ancestor_locallabel"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "crossapp_tenant_ancestor_locallabel"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "crossapp_tenant_ancestor_locallabel";
        """,
        ),

        # Updated at Trigger on "crossapp_tenant_ancestor_tenantedancestor" table! [SQL:82921a0f543d]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "crossapp_tenant_ancestor_tenantedancestor" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "crossapp_tenant_ancestor_tenantedancestor";
        """,
        ),

        # Soft Delete Rule on "crossapp_tenant_ancestor_tenantedancestor" table! [SQL:b8abd6548fda]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "crossapp_tenant_ancestor_tenantedancestor"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "crossapp_tenant_ancestor_tenantedancestor"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "crossapp_tenant_ancestor_tenantedancestor";
        """,
        ),

        # Soft Delete Related Rule on "crossapp_tenant_ancestor_tenantedancestor" that is related to "crossapp_tenant_ancestor_locallabel"! [SQL:8bb2ac8e8f47]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_crossapp_tenant_ancestor_tenantedancestor"
                AS ON UPDATE TO "crossapp_tenant_ancestor_locallabel"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "crossapp_tenant_ancestor_tenantedancestor"
                    SET _deleted_at = NOW()
                    WHERE "label_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_crossapp_tenant_ancestor_tenantedancestor" ON "crossapp_tenant_ancestor_locallabel";
        """,
        ),

        # Tenant RLS on "crossapp_tenant_ancestor_tenantedancestor" table! [POLICY:3f4bb4ab26ad] [SQL:7d16e325cb2f]
        migrations.RunSQL(
            sql=[
                """CREATE POLICY tenant_scope ON crossapp_tenant_ancestor_tenantedancestor FOR ALL TO PUBLIC
            USING ((SELECT current_setting('tenant.bypass', true)) = 'on' OR (crossapp_tenant_ancestor_tenantedancestor.label_id::text = ANY(string_to_array((SELECT current_setting('tenant.label', true)), ','))))
            WITH CHECK ((SELECT current_setting('tenant.bypass', true)) = 'on' OR (crossapp_tenant_ancestor_tenantedancestor.label_id::text = ANY(string_to_array((SELECT current_setting('tenant.label', true)), ','))))""",
                """ALTER TABLE crossapp_tenant_ancestor_tenantedancestor ENABLE ROW LEVEL SECURITY""",
                """ALTER TABLE crossapp_tenant_ancestor_tenantedancestor FORCE ROW LEVEL SECURITY""",
            ],
            reverse_sql=[
                """ALTER TABLE crossapp_tenant_ancestor_tenantedancestor NO FORCE ROW LEVEL SECURITY""",
                """ALTER TABLE crossapp_tenant_ancestor_tenantedancestor DISABLE ROW LEVEL SECURITY""",
                """DROP POLICY IF EXISTS tenant_scope ON crossapp_tenant_ancestor_tenantedancestor""",
            ],
        ),

    ]
