# Generated by Django 5.2.18 on 2026-10-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue66_retaken', '0003_rename_crew_squad'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='squad',
            new_name='squad_deleted_at',
            old_name='crew_deleted_at',
        ),
        migrations.AlterField(
            model_name='squad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='issue66_retaken.boss'),
        ),
    ]
