# Generated by makeguitarmigrations command! [DIGEST:e1c03284c0c4b3112b0b460bbd3d6530]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0082_auto_enforcement_stamp_function'),
        ('issue66_retaken', '0007_auto_enforcement'),
    ]

    operations = [
        # Updated at Trigger on "issue66_retaken_crew" table! [SQL:9557903eb45d]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "issue66_retaken_crew"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "issue66_retaken_crew";
        """,
        ),

        # Soft Delete Rule on "issue66_retaken_crew" table! [SQL:318ab6a462b3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "issue66_retaken_crew"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "issue66_retaken_crew"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "issue66_retaken_crew";
        """,
        ),

    ]
