# Generated by Django, matching the real shape of tests/testapp/migrations/0001_initial.py's
# Band/Album pair before the 1.1.0 SQL-inlining change (see git show 2ba86a3^:tests/testapp).

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LegacyBand',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='LegacyAlbum',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                (
                    'band',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='albums',
                        to='legacy_migrations.legacyband',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [
                    models.Index(
                        condition=models.Q(('_deleted_at__isnull', True)),
                        fields=['_deleted_at'],
                        name='legacyalbum_deleted_at',
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name='legacyband',
            index=models.Index(
                condition=models.Q(('_deleted_at__isnull', True)),
                fields=['_deleted_at'],
                name='legacyband_deleted_at',
            ),
        ),
    ]
