# Generated by Django 5.2.15 on 2026-08-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crossapp_tenant_ancestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantedChild',
            fields=[
                ('tenantedancestor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crossapp_tenant_ancestor.tenantedancestor')),
                ('seats', models.IntegerField(default=0)),
            ],
            bases=('crossapp_tenant_ancestor.tenantedancestor',),
        ),
    ]
