# Generated by makeguitarmigrations command! [DIGEST:87d56be425ed131de0770844e3298111]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossapp_tenant_ancestor', '0002_tenantedancestor_label'),
        ('testapp', '0017_auto_enforcement_parent_trigger_function'),
        ('crossapp_tenant_child', '0001_initial'),
    ]

    operations = [
        # MTI Updated at Trigger on "crossapp_tenant_child_tenantedchild" table (parent "crossapp_tenant_ancestor_tenantedancestor")! [SQL:67047f36bd14]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "crossapp_tenant_child_tenantedchild" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_parent_updated_at(
                    '', 'crossapp_tenant_ancestor_tenantedancestor', 'id', 'tenantedancestor_ptr_id'
                );
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "crossapp_tenant_child_tenantedchild";
        """,
        ),

        # MTI Soft Delete Rule on "crossapp_tenant_child_tenantedchild" table (parent "crossapp_tenant_ancestor_tenantedancestor")! [SQL:89a2d5c62d24]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "crossapp_tenant_child_tenantedchild"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "crossapp_tenant_ancestor_tenantedancestor"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."tenantedancestor_ptr_id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "crossapp_tenant_child_tenantedchild";
        """,
        ),

        # Tenant RLS on "crossapp_tenant_child_tenantedchild" table! [POLICY:1209285662f1] [SQL:5832b323a8a9]
        migrations.RunSQL(
            sql=[
                """CREATE POLICY tenant_scope ON crossapp_tenant_child_tenantedchild FOR ALL TO PUBLIC
            USING ((SELECT current_setting('tenant.bypass', true)) = 'on' OR (EXISTS (
                SELECT 1 FROM crossapp_tenant_ancestor_tenantedancestor AS _guitars_owner
                WHERE _guitars_owner.id = crossapp_tenant_child_tenantedchild.tenantedancestor_ptr_id
                  AND _guitars_owner.label_id::text = ANY(string_to_array((SELECT current_setting('tenant.label', true)), ','))
            )))
            WITH CHECK ((SELECT current_setting('tenant.bypass', true)) = 'on' OR (EXISTS (
                SELECT 1 FROM crossapp_tenant_ancestor_tenantedancestor AS _guitars_owner
                WHERE _guitars_owner.id = crossapp_tenant_child_tenantedchild.tenantedancestor_ptr_id
                  AND _guitars_owner.label_id::text = ANY(string_to_array((SELECT current_setting('tenant.label', true)), ','))
            )))""",
                """ALTER TABLE crossapp_tenant_child_tenantedchild ENABLE ROW LEVEL SECURITY""",
                """ALTER TABLE crossapp_tenant_child_tenantedchild FORCE ROW LEVEL SECURITY""",
            ],
            reverse_sql=[
                """ALTER TABLE crossapp_tenant_child_tenantedchild NO FORCE ROW LEVEL SECURITY""",
                """ALTER TABLE crossapp_tenant_child_tenantedchild DISABLE ROW LEVEL SECURITY""",
                """DROP POLICY IF EXISTS tenant_scope ON crossapp_tenant_child_tenantedchild""",
            ],
        ),

    ]
