# Generated by Django 5.2.15 on 2026-08-22 07:49

import django.db.models.deletion
import django.db.models.functions.datetime
import guitars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crossapp_dependent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
                ('target', guitars.models.OwningForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossapp_dependent.shared')),
            ],
        ),
    ]
