# Generated by makeguitarmigrations command! [DIGEST:50f6323087247d8abe368ef31243dc8e]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossapp_dependent', '0001_initial'),
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('crossapp_owner', '0001_initial'),
    ]

    operations = [
        # Updated at Trigger on "crossapp_owner_owner" table! [SQL:7ac174cdac84]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "crossapp_owner_owner" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "crossapp_owner_owner";
        """,
        ),

        # Soft Delete Rule on "crossapp_owner_owner" table! [SQL:8553fcee1744]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "crossapp_owner_owner"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "crossapp_owner_owner"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "crossapp_owner_owner";
        """,
        ),

        # Soft Delete Owned Rule on "crossapp_dependent_shared" that is owned by "crossapp_owner_owner" via "target_id"! [SQL:a46984026c75]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_25_crossapp_dependent_shared_9_target_id"
                AS ON UPDATE TO "crossapp_owner_owner"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "crossapp_dependent_shared"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."target_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "crossapp_owner_owner" AS guitars_owner
                          WHERE guitars_owner."target_id" = old."target_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "crossapp_dependent_localowner" AS guitars_owner_1
                          WHERE guitars_owner_1."target_id" = old."target_id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_25_crossapp_dependent_shared_9_target_id" ON "crossapp_owner_owner";
        """,
        ),

    ]
