"""The instrument ladder: abstract bases named by string count, one rung per capability.

Each rung is a capability the **database** enforces, not a bag of helpers::

    TarModel          "tar" = string. The shared root: .update() and cached-property
                      invalidation. Adds no columns and no database behaviour.
    DutarModel   (2)  + DB-managed _created_at / _updated_at, kept honest by a
                      statement-level trigger.
    SetarModel   (3)  + PostgreSQL soft deletion: a rule, three managers, cascades.
    GuitarModel  (6)  + tenancy: a tenant FK, tenant-scoped managers, and an RLS policy.

Pick the rung whose *guarantees* you want; every capability is also available as a
standalone mixin (``UpdatableModel``, ``HasCachedPropertyModel``, ``DatedModel``,
``SoftDeletableModel``) for models that need one without the ones below it.
"""

from contextlib import nullcontext

from asgiref.sync import sync_to_async
from django.conf import settings
from django.db import transaction
from django.db.models import CASCADE, DateTimeField, ForeignKey
from django.db.models.base import Model
from django.db.models.functions import Now
from django.utils.functional import cached_property

from guitars.tenancy import TenantedManager
from guitars.tenancy.checks import register_checks

from .soft_deletion import AllObjectsManager, ArchiveManager, LiveManager, SoftDeletableModel


class DatedModel(Model):
    """Abstract model with auto-managed ``_created_at`` and ``_updated_at`` fields.

    Both default to ``NOW()`` at the database level. ``_updated_at`` is kept
    current by a PostgreSQL statement-level trigger (not Django signals),
    generated by ``makeguitarmigrations``. This means timestamps are
    accurate even for raw SQL or bulk operations that bypass ``.save()``.
    """

    _created_at = DateTimeField(verbose_name='Created at', db_default=Now(), editable=False)
    _updated_at = DateTimeField(verbose_name='Updated at', db_default=Now(), editable=False)

    class Meta:
        abstract = True


class UpdatableModel(Model):
    """Abstract model that adds a convenience ``.update(**attrs)`` method.

    Sets attributes and saves in one call with fine-grained control.
    """

    class Meta:
        abstract = True

    @cached_property
    def _updatable_fields(self) -> set[str]:
        fields = set()
        for field in self._meta._get_fields(reverse=False, include_hidden=True):
            fields.add(field.name)
            column = getattr(field, 'column', None)
            if column:  # To accept foreign keys in fk_id format! (relations have no column)
                fields.add(column)

        return fields

    def _prepare_update(
        self,
        _save: bool,
        _save_all_fields: bool,
        _raise_for_excessive: bool,
        attrs: dict[str, object],
    ) -> tuple[dict[str, object], set[str] | None]:
        """Validate attrs and set non-M2M fields in memory.

        Returns ``(m2m_attrs, update_fields)`` ready for the save step.
        ``update_fields`` is ``None`` when all fields should be saved.
        """
        fields = self._updatable_fields
        m2m_fields = {field.name for field in self._meta.local_many_to_many}
        given_fields = set(attrs.keys())
        excessive_fields = given_fields - fields
        updating_fields = (fields & given_fields) - m2m_fields

        if excessive_fields and _raise_for_excessive:
            raise ValueError(f'Invalid arguments: {excessive_fields}. (valid choices: {fields})')

        m2m_attrs: dict[str, object] = {}
        for attr, attr_value in attrs.items():
            if attr in m2m_fields:
                m2m_attrs[attr] = attr_value
            elif attr in updating_fields:
                setattr(self, attr, attr_value)

        if not _save and m2m_attrs:
            raise ValueError('Cannot update m2m fields without saving the instance!')

        update_fields = updating_fields if not _save_all_fields and updating_fields else None
        return m2m_attrs, update_fields

    def update(
        self,
        _save=True,
        _save_all_fields=False,
        _raise_for_excessive=True,
        _disable_signals=False,
        **attrs,
    ):
        """Set attributes on the instance and optionally persist to the database.

        Only the fields passed as ``**attrs`` are written to the DB (via
        ``update_fields``), unless ``_save_all_fields=True``.

        When called with ``_save=False``, attributes are set in memory only.
        A subsequent call with ``_save=True`` will **not** include those
        earlier attributes unless ``_save_all_fields=True`` is also passed.

        M2M fields are handled via ``.set(values, clear=True)`` and require
        ``_save=True``.

        The save runs inside ``transaction.atomic()``.
        """
        m2m_attrs, update_fields = self._prepare_update(
            _save, _save_all_fields, _raise_for_excessive, attrs
        )

        if _save:
            from guitars.signals import DisableSignals

            signals_context = DisableSignals() if _disable_signals else nullcontext()
            with signals_context:
                with transaction.atomic():
                    self.save(update_fields=update_fields)
                    for attr, attr_value in m2m_attrs.items():
                        getattr(self, attr).set(attr_value, clear=True)

    async def aupdate(
        self,
        _save=True,
        _save_all_fields=False,
        _raise_for_excessive=True,
        _disable_signals=False,
        **attrs,
    ):
        """Async version of ``.update()``. See ``.update()`` for full documentation."""
        await sync_to_async(self.update)(
            _save=_save,
            _save_all_fields=_save_all_fields,
            _raise_for_excessive=_raise_for_excessive,
            _disable_signals=_disable_signals,
            **attrs,
        )


class HasCachedPropertyModel(Model):
    """Abstract model that auto-invalidates ``@cached_property`` on refresh.

    Overrides ``refresh_from_db()`` to clear all cached properties, preventing
    stale in-memory values after a database refresh.
    """

    class Meta:
        abstract = True

    def expire_cached_properties(self, *properties):
        obj_dict = self.__class__.__dict__
        properties = properties or obj_dict.keys()
        for key in properties:
            if isinstance(obj_dict[key], cached_property):
                self.__dict__.pop(key, None)

    def refresh_from_db(self, *args, **kwargs):
        self.expire_cached_properties()
        return super().refresh_from_db(*args, **kwargs)


class TarModel(UpdatableModel, HasCachedPropertyModel):
    """The root: the ``.update()`` helper (``UpdatableModel``) and cached-property
    invalidation (``HasCachedPropertyModel``), nothing else.

    "Tār" is Persian for *string* — the thing every rung above is counted in. It has no
    number of its own because it carries no database capability: no columns, no triggers,
    no rules. The lightest base, for a model that wants the two ergonomic mixins and
    nothing else.

    (The introspection helpers — ``app_label()``, ``model_name()``, ``class_name()`` and
    the field-listing ``__repr__`` — stay one rung up on ``DutarModel``, where they have
    always been. Nothing about them needs timestamps; they are left in place so the rung
    shift is a pure rename for existing consumers rather than a rename *and* a
    redistribution.)
    """

    class Meta:
        abstract = True


class DutarModel(DatedModel, TarModel):
    """The two-string rung: ``TarModel`` plus database-managed timestamps
    (``DatedModel``).

    Adds ``_created_at`` / ``_updated_at`` — both defaulting to ``NOW()`` in the database,
    with ``_updated_at`` ridden by a statement-level trigger so it stays honest under
    ``bulk_update`` and raw SQL — on top of ``.update()`` and cached-property
    invalidation. Two columns, two strings.
    """

    class Meta:
        abstract = True

    @classmethod
    def app_label(cls) -> str:
        """Returns app label in lowercase."""
        if not (hasattr(cls, '_meta') and cls._meta.app_label):
            raise AttributeError(f'{cls.__name__}._meta.app_label is not set!')

        return cls._meta.app_label

    @classmethod
    def model_name(cls) -> str:
        """Returns model name in lowercase"""
        if not (hasattr(cls, '_meta') and cls._meta.model_name):
            raise AttributeError(f'{cls.__name__}._meta.model_name is not set!')

        return cls._meta.model_name

    @classmethod
    def class_name(cls) -> str:
        """Returns class name"""
        return cls.__name__

    def __repr__(self) -> str:
        # Only concrete non-M2M fields — M2M / reverse relations on an unsaved
        # instance raise ValueError formatted with the instance itself, which
        # would recurse back into __repr__.
        representation = f'<{self.__class__.__name__} ID:{self.pk} - '
        for field in self._meta.fields:
            if not field.editable:
                continue
            value = getattr(self, field.name)
            if value is None:
                continue
            representation += f'{field.name}: {value} - '
        return representation + '>'


class SetarModel(DutarModel, SoftDeletableModel):
    """The three-string rung: ``DutarModel`` plus PostgreSQL soft deletion.

    Adds ``_deleted_at`` and the three managers (``objects`` / ``_archives`` /
    ``_all_objects``); ``.delete()`` becomes a soft delete, cascading to related
    soft-deletable models, because a PostgreSQL rule does the work rather than a
    ``save()`` override. ``Meta`` inherits ``SoftDeletableModel``'s soft-delete partial
    index and default manager.

    The right base for most models: everything the kit enforces about a *row*, without
    committing to multi-tenancy. Reach for ``GuitarModel`` only when rows belong to a
    tenant.

    Naming note: "se-tār" is Persian for "three strings", which is why this rung sits at
    three. The modern instrument actually has four — a fourth string was added in the 18th
    century (attributed to Moshtāq Ali Shāh). The ladder follows the etymology, not the
    current string count.
    """

    class Meta(SoftDeletableModel.Meta):
        abstract = True


# Both read once, at import, because that is when the field has to be named -- and both
# private for the same reason. A consumer importing them would be holding a snapshot that
# `override_settings` cannot move, which reads like live configuration and is not. The
# supported way to ask a model what it is scoped on is `guitars.tenancy.tenant_spec(Model)`,
# which is derived per model from the manager and therefore always current.
_TENANT_MODEL = getattr(settings, 'GUITARS_TENANT_MODEL', None)
_TENANT_FIELD = getattr(settings, 'GUITARS_TENANT_FIELD', 'tenant')


class GuitarModel(SetarModel):
    """The six-string rung: ``SetarModel`` plus multi-tenancy. The full kit.

    On top of soft deletion and timestamps, a concrete subclass gets:

    * a non-null ``ForeignKey`` to ``settings.GUITARS_TENANT_MODEL``, named
      ``settings.GUITARS_TENANT_FIELD`` (default ``'tenant'``), ``on_delete=CASCADE`` and
      ``editable=False``;
    * all three managers wrapped in :func:`~guitars.tenancy.TenantedManager`, so a read
      without an active scope raises ``TenantScopeError`` instead of returning every
      tenant's rows;
    * a ``tenant_scope`` row-level-security policy, generated by
      ``makeguitarmigrations``, which enforces the same frame on *every* statement —
      joins, cascades, ``_base_manager``, ``instance.save()`` and raw SQL included.

    ``autofill=True`` is passed explicitly, overriding ``GUITARS_TENANT_AUTOFILL``: this
    field is framework-owned and ``editable=False``, so making every call site name it
    would be ceremony with no payoff. It is refused for a collection scope
    (``tenant(tenant=[a, b])`` names no single value) — pass the tenant explicitly there.

    **Without ``GUITARS_TENANT_MODEL`` this rung is inert**, and deliberately so rather
    than an import-time crash: ``guitars.models`` must stay importable for the projects
    that use the lower rungs. Subclassing it in that state is caught by the
    ``guitars.tenancy.E003`` system check, which ``manage.py check``, ``runserver``,
    ``migrate`` and ``makemigrations`` all run.

    **Cascade consequence.** The tenant FK is ``CASCADE``, so if the tenant model is itself
    soft-deletable, ``makeguitarmigrations`` writes one ``soft_delete_related_*`` ``DO
    ALSO`` rule per tenanted model onto the tenant table. Soft-deleting one tenant then
    fires N ``UPDATE``s in a single statement. Correct, and cheap next to the alternative
    of orphaned rows — but it scales with the number of tenanted models, not with rows.
    """

    #: Whether the tenant FK and the scoped managers were actually installed below.
    #: Read by the system check, which cannot import this class at module scope (the
    #: tenancy package is imported *by* this module) and must not re-derive the condition.
    _guitars_tenancy_installed = False

    class Meta(SetarModel.Meta):
        abstract = True

        # base_manager_name is deliberately left unset, so ``_base_manager`` stays
        # Django's auto-created plain Manager.
        #
        # Pointing it at a tenant-scoped manager is tempting -- ``_base_manager`` is what
        # fetches related objects, so scoping it would filter ``select_related`` too -- and
        # it is wrong for three reasons:
        #
        # 1. Django's own rule is that a base manager must not filter rows. A FK pointing
        #    at a row the filter hides raises RelatedObjectDoesNotExist, which names the
        #    wrong problem.
        # 2. ``_base_manager`` is on the ``save()`` path (``Model._do_insert`` /
        #    ``_do_update``), and ``QuerySet._insert`` / ``_update`` are ``queryset_only =
        #    False``, so they are not on the deny-list a missing scope raises from. Writes
        #    would pass while reads denied: enforcement that is partial in a way nobody
        #    could predict from the outside.
        # 3. ``_base_manager`` is the canonical example of a path no manager guards, and
        #    the row-level-security policy covers it completely. Half-covering it in Python
        #    would add a failure mode without closing a hole.


def _install_tenancy(tenant_model: str, field_name: str) -> None:
    """Contribute the tenant field and the scoped managers to ``GuitarModel``.

    A function rather than module-level statements so the loop variables do not linger as
    module globals, and so the whole operation has one name to point at.

    Contributed after the class body rather than declared in it, because the field's *name*
    comes from a setting and a class body cannot bind a computed attribute name.
    ``add_to_class`` is the same entry point Django's own metaclass uses, and an abstract
    base has its ``local_fields`` and ``local_managers`` copied down when a concrete
    subclass is defined -- which happens later, at consumer import time -- so anything
    added here reaches every subclass exactly as a declared one would.
    """
    GuitarModel.add_to_class(
        field_name,
        ForeignKey(
            tenant_model,
            on_delete=CASCADE,
            # CASCADE, not PROTECT: a tenant's rows are meaningless without it, and the
            # database-level soft delete means "cascade" archives rather than destroys.
            related_name='%(app_label)s_%(class)s_set',
            # Templated, because every tenanted model in every app would otherwise collide
            # on the same reverse accessor.
            editable=False,
            # Framework-owned: kept out of ModelForms and the admin, and filled from the
            # active scope by the write guard.
        ),
    )
    for name, manager_class in (
        ('objects', LiveManager),
        ('_archives', ArchiveManager),
        ('_all_objects', AllObjectsManager),
    ):
        # All three, not just the default: ``_archives`` and ``_all_objects`` exist to see
        # rows ``objects`` hides, and an unscoped one would see every tenant's.
        GuitarModel.add_to_class(
            name,
            TenantedManager(
                _manager_class=manager_class,
                autofill=True,
                **{field_name: field_name},
            ),
        )
    GuitarModel._guitars_tenancy_installed = True


# Registered unconditionally, and deliberately *not* behind ``tenancy.install()``.
#
# ``install()`` reaches this module two ways -- ``GuitarsConfig.ready()`` and
# ``TenantedManager()`` -- and with GUITARS_TENANT_MODEL unset neither fires: the manager is
# never constructed, and a project using guitars as a pure library has no INSTALLED_APPS
# entry for the AppConfig hook. That combination is exactly the one E003 exists to catch, so
# leaving the checks to ``install()`` meant they were absent from the only case that needed
# them. Checks cost nothing to register and run on demand; the enforcement machinery
# (an execute wrapper on every query, a pre_save receiver) is not free, so that stays
# behind the manager that asks for it.
register_checks()

if _TENANT_MODEL:
    _install_tenancy(_TENANT_MODEL, _TENANT_FIELD)
