from collections import defaultdict

from django.db import connection, transaction
from django.db.models import CASCADE, DateTimeField, Index, Manager, Q, QuerySet, sql
from django.db.models.base import Model

from guitars.sql import SWITCH_OFF_HARD_DELETION, SWITCH_ON_HARD_DELETION


class LiveQuerySet(QuerySet):
    """QuerySet scoped to live (non-deleted) records via ``_deleted_at IS NULL``."""

    @property
    def lives(self):
        return self.filter(_deleted_at__isnull=True)


class LiveManager(Manager):
    """Default manager — returns only live records (``_deleted_at IS NULL``)."""

    _queryset_class = LiveQuerySet

    def get_queryset(self) -> LiveQuerySet:
        return LiveQuerySet(model=self.model, using=self._db, hints=self._hints).lives


class HardDeletableQuerySet(LiveQuerySet):
    """QuerySet that can access archived records and perform hard deletes.

    ``.hard_delete()`` temporarily sets the PostgreSQL session variable
    ``rules.hard_deletion = 'on'`` so the soft-delete rule is bypassed,
    then executes a real ``DELETE`` statement inside a transaction.
    """

    @property
    def archives(self):
        return self.filter(_deleted_at__isnull=False)

    def hard_delete(self):
        """Permanently remove matching rows from the database."""
        with connection.cursor() as cursor:
            query = self.query.clone()
            query.__class__ = sql.DeleteQuery
            query, params = query.sql_with_params()
            with transaction.atomic():
                return cursor.execute(
                    f'{SWITCH_ON_HARD_DELETION}\n{query};\n{SWITCH_OFF_HARD_DELETION}', params
                )

    hard_delete.queryset_only = True  # ty:ignore[unresolved-attribute]


class ArchiveManager(Manager):
    """Manager that returns only soft-deleted records (``_deleted_at IS NOT NULL``)."""

    _queryset_class = HardDeletableQuerySet

    def get_queryset(self) -> HardDeletableQuerySet:
        return HardDeletableQuerySet(model=self.model, using=self._db, hints=self._hints).archives


class AllObjectsManager(Manager):
    """ """

    _queryset_class = HardDeletableQuerySet

    def get_queryset(self) -> HardDeletableQuerySet:
        return HardDeletableQuerySet(model=self.model, using=self._db, hints=self._hints)

    @property
    def lives(self):
        return self.get_queryset().lives

    @property
    def archives(self):
        return self.get_queryset().archives


class SoftDeletableModel(Model):
    """Abstract model that enables PostgreSQL-level soft deletion.

    Deletion logic lives entirely in the database via PostgreSQL rules
    generated by ``makeguitarmigrations``. Calling Django's ``.delete()``
    is intercepted by a rule that sets ``_deleted_at = NOW()`` instead of
    removing the row.

    Three managers control record visibility:

    - ``objects`` (``LiveManager``) — only live records (default).
    - ``_archives`` (``ArchiveManager``) — only soft-deleted records.
    - ``_all_objects`` (``AllObjectManager``) — everything.
    """

    _deleted_at = DateTimeField(
        verbose_name='Deleted at',
        null=True,
        editable=False,
    )

    objects = LiveManager()  # ```.objects``` attribute excludes "archived" records!

    _archives = ArchiveManager()  # ```.archived``` attribute excludes "active" records!
    _all_objects = AllObjectsManager()  # ```._all_objects``` attribute returns all records!

    class Meta:
        abstract = True
        default_manager_name = 'objects'
        indexes = [
            Index(
                fields=['_deleted_at'],
                condition=Q(_deleted_at__isnull=True),
                name='%(class)s_deleted_at',
            ),
        ]

    @property
    def cls(self):
        return self.__class__

    @property
    def is_deleted(self):
        return bool(self._deleted_at)

    @property
    def is_alive(self):
        return not self.is_deleted

    def hard_delete(self):
        """Soft-delete first, then permanently remove this instance and all CASCADE-related rows.

        Two-phase approach:
        1. ``self.delete()`` — triggers the PG soft-delete rule, which also fires the PG
           cascade-soft-delete rules for every related ``SoftDeletableModel``.  The call is
           idempotent: the rule's ``WHERE _deleted_at IS NULL`` guard makes it a no-op when
           the row is already soft-deleted.
        2. DFS collection + hard-delete — walks ``on_delete=CASCADE`` FK relations via
           ``_all_objects`` (so already-soft-deleted rows are included), builds a child-first
           deletion order, and bulk-hard-deletes each model's rows inside one transaction.

        Note: Django's ``on_delete=CASCADE`` is Python-level (``Collector``-based).  Django
        does **not** create ``ON DELETE CASCADE`` constraints in PostgreSQL, so a raw DELETE
        on the parent would be rejected by the DB's FK check.  That is why we must collect
        and delete children before parents ourselves.
        """
        using = self._state.db
        pk = self.pk  # save before Phase 1 resets self.pk to None
        to_delete: dict[type, set] = defaultdict(set)
        model_order: list[type] = []

        def _collect(model: type, pks: set) -> None:
            new_pks = pks - to_delete[model]
            if not new_pks:
                return
            to_delete[model].update(new_pks)
            for relation in model._meta.related_objects:  # ty:ignore[unresolved-attribute]
                if relation.on_delete is not CASCADE:
                    continue
                related_model = relation.related_model
                mgr = (
                    related_model._all_objects
                    if hasattr(related_model, '_all_objects')
                    else related_model._default_manager
                )
                child_pks = set(
                    mgr.using(using)
                    .filter(**{f'{relation.field.name}__in': new_pks})
                    .values_list('pk', flat=True)
                )
                _collect(related_model, child_pks)
            if model not in model_order:
                model_order.append(model)

        with transaction.atomic():
            # Phase 1 — soft-delete first (idempotent; PG rules cascade to related objects).
            self.delete()

            # Phase 2 — collect all related rows (now all soft-deleted) and hard-delete
            # in child-first order so no FK constraint is violated.
            # NOTE: self.pk is None after Phase 1 (Django clears it post-delete), use saved pk.
            _collect(self.__class__, {pk})

            for model in model_order:
                pks = list(to_delete[model])
                if hasattr(model, '_all_objects'):
                    model._all_objects.using(using).filter(pk__in=pks).hard_delete()  # ty:ignore[unresolved-attribute]
                else:
                    model._default_manager.using(using).filter(pk__in=pks).delete()  # ty:ignore[unresolved-attribute]
