# Generated by makeguitarmigrations command! [DIGEST:2b5d5a551724ce4e0ae96941ef135220]

from django.db import migrations

from guitars import sql


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        # Define function for updated at triggers!
        migrations.RunSQL(
            sql=sql.CREATE_UPDATED_AT_TRIGGER_FUNCTION,
            reverse_sql=sql.DROP_UPDATED_AT_TRIGGER_FUNCTION,
        ),

    ]
