# Generated by makeguitarmigrations command! [DIGEST:ddb8b2548b6b56c99c465a96a4dda9c5]

from django.db import migrations

from guitars import sql


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_auto_advanced_trigger_function"),
        ('testapp', '0002_auto_advanced_trigger_function'),
    ]

    operations = [
        # Updated at Trigger on "testapp_genre" table!
        migrations.RunSQL(
            sql=sql.CREATE_UPDATED_AT_TRIGGER.format(table='testapp_genre', primary_key='id'),
            reverse_sql=sql.DROP_UPDATED_AT_TRIGGER.format(table='testapp_genre'),
        ),

        # Updated at Trigger on "testapp_band" table!
        migrations.RunSQL(
            sql=sql.CREATE_UPDATED_AT_TRIGGER.format(table='testapp_band', primary_key='id'),
            reverse_sql=sql.DROP_UPDATED_AT_TRIGGER.format(table='testapp_band'),
        ),

        # Soft Delete Rule on "testapp_band" table!
        migrations.RunSQL(
            sql=sql.CREATE_SOFT_DELETE_RULE.format(table='testapp_band', primary_key='id'),
            reverse_sql=sql.DROP_SOFT_DELETE_RULE.format(table='testapp_band'),
        ),

        # Updated at Trigger on "testapp_album" table!
        migrations.RunSQL(
            sql=sql.CREATE_UPDATED_AT_TRIGGER.format(table='testapp_album', primary_key='id'),
            reverse_sql=sql.DROP_UPDATED_AT_TRIGGER.format(table='testapp_album'),
        ),

        # Soft Delete Rule on "testapp_album" table!
        migrations.RunSQL(
            sql=sql.CREATE_SOFT_DELETE_RULE.format(table='testapp_album', primary_key='id'),
            reverse_sql=sql.DROP_SOFT_DELETE_RULE.format(table='testapp_album'),
        ),

        # Soft Delete Related Rule on "testapp_album" that is related to "testapp_band"!
        migrations.RunSQL(
            sql=sql.CREATE_SOFT_DELETE_RELATED_OBJECTS_RULE.format(
                table='testapp_band',
                related_table='testapp_album',
                primary_key='id',
                foreign_key='band_id',
            ),
            reverse_sql=sql.DROP_SOFT_DELETE_RELATED_OBJECTS_RULE.format(
                table='testapp_band', related_table='testapp_album'
            ),
        ),

    ]
