# Generated by makeguitarmigrations command! [DIGEST:e446c8b6aed0224449cde61e1032f48c]

from django.db import migrations

from guitars import sql


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_auto_advanced_trigger_function"),
        ('testapp', '0005_ensemble_section_orchestra_and_more'),
    ]

    operations = [
        # Define function for MTI parent updated at triggers!
        migrations.RunSQL(
            sql=sql.CREATE_PARENT_UPDATED_AT_TRIGGER_FUNCTION,
            reverse_sql=sql.DROP_PARENT_UPDATED_AT_TRIGGER_FUNCTION,
        ),

    ]
