# Generated by makeguitarmigrations command! [DIGEST:c6f44e4023086a8086cf1f3e3c33594b]

from django.db import migrations

from guitars import sql


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_auto_advanced_trigger_function"),
        ('testapp', '0006_auto_advanced_parent_trigger_function'),
    ]

    operations = [
        # Updated at Trigger on "testapp_ensemble" table!
        migrations.RunSQL(
            sql=sql.CREATE_UPDATED_AT_TRIGGER.format(table='testapp_ensemble', primary_key='id'),
            reverse_sql=sql.DROP_UPDATED_AT_TRIGGER.format(table='testapp_ensemble'),
        ),

        # Soft Delete Rule on "testapp_ensemble" table!
        migrations.RunSQL(
            sql=sql.CREATE_SOFT_DELETE_RULE.format(table='testapp_ensemble', primary_key='id'),
            reverse_sql=sql.DROP_SOFT_DELETE_RULE.format(table='testapp_ensemble'),
        ),

        # MTI Updated at Trigger on "testapp_orchestra" table (parent "testapp_ensemble")!
        migrations.RunSQL(
            sql=sql.CREATE_PARENT_UPDATED_AT_TRIGGER.format(
                child_table='testapp_orchestra',
                parent_table='testapp_ensemble',
                parent_pk='id',
                child_pk='ensemble_ptr_id',
            ),
            reverse_sql=sql.DROP_PARENT_UPDATED_AT_TRIGGER.format(child_table='testapp_orchestra'),
        ),

        # MTI Soft Delete Rule on "testapp_orchestra" table (parent "testapp_ensemble")!
        migrations.RunSQL(
            sql=sql.CREATE_MTI_SOFT_DELETE_RULE.format(
                child_table='testapp_orchestra',
                parent_table='testapp_ensemble',
                parent_pk='id',
                child_pk='ensemble_ptr_id',
            ),
            reverse_sql=sql.DROP_MTI_SOFT_DELETE_RULE.format(child_table='testapp_orchestra'),
        ),

        # MTI Updated at Trigger on "testapp_chamberorchestra" table (parent "testapp_ensemble")!
        migrations.RunSQL(
            sql=sql.CREATE_PARENT_UPDATED_AT_TRIGGER.format(
                child_table='testapp_chamberorchestra',
                parent_table='testapp_ensemble',
                parent_pk='id',
                child_pk='orchestra_ptr_id',
            ),
            reverse_sql=sql.DROP_PARENT_UPDATED_AT_TRIGGER.format(child_table='testapp_chamberorchestra'),
        ),

        # MTI Soft Delete Rule on "testapp_chamberorchestra" table (parent "testapp_ensemble")!
        migrations.RunSQL(
            sql=sql.CREATE_MTI_SOFT_DELETE_RULE.format(
                child_table='testapp_chamberorchestra',
                parent_table='testapp_ensemble',
                parent_pk='id',
                child_pk='orchestra_ptr_id',
            ),
            reverse_sql=sql.DROP_MTI_SOFT_DELETE_RULE.format(child_table='testapp_chamberorchestra'),
        ),

        # Updated at Trigger on "testapp_section" table!
        migrations.RunSQL(
            sql=sql.CREATE_UPDATED_AT_TRIGGER.format(table='testapp_section', primary_key='id'),
            reverse_sql=sql.DROP_UPDATED_AT_TRIGGER.format(table='testapp_section'),
        ),

        # Soft Delete Rule on "testapp_section" table!
        migrations.RunSQL(
            sql=sql.CREATE_SOFT_DELETE_RULE.format(table='testapp_section', primary_key='id'),
            reverse_sql=sql.DROP_SOFT_DELETE_RULE.format(table='testapp_section'),
        ),

        # Soft Delete Related Rule on "testapp_section" that is related to "testapp_ensemble"!
        migrations.RunSQL(
            sql=sql.CREATE_SOFT_DELETE_RELATED_OBJECTS_RULE.format(
                table='testapp_ensemble',
                related_table='testapp_section',
                primary_key='id',
                foreign_key='orchestra_id',
            ),
            reverse_sql=sql.DROP_SOFT_DELETE_RELATED_OBJECTS_RULE.format(
                table='testapp_ensemble', related_table='testapp_section'
            ),
        ),

    ]
