# Generated by Django 5.2.15 on 2026-07-06 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_advanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_albums', to='testapp.band'),
        ),
        migrations.AddField(
            model_name='riff',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riffs', to='testapp.band'),
        ),
    ]
