# Generated by Django 5.2.15 on 2026-07-30 16:28

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0008_album_producer_riff_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [
                    models.Index(
                        condition=models.Q(('_deleted_at__isnull', True)),
                        fields=['_deleted_at'],
                        name='label_deleted_at',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                (
                    'label',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='testapp.label',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('body', models.CharField(max_length=200)),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='testapp.release',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='WorldTour',
            fields=[
                (
                    'tour_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='testapp.tour',
                    ),
                ),
                ('continents', models.IntegerField(default=1)),
            ],
            bases=('testapp.tour',),
        ),
        migrations.AddField(
            model_name='tour',
            name='label',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(app_label)s_%(class)s_set',
                to='testapp.label',
            ),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                (
                    'label',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='testapp.label',
                    ),
                ),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tracks',
                        to='testapp.release',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('venue', models.CharField(max_length=100)),
                (
                    'label',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bookings',
                        to='testapp.label',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [
                    models.Index(
                        condition=models.Q(('_deleted_at__isnull', True)),
                        fields=['_deleted_at'],
                        name='booking_deleted_at',
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(
                condition=models.Q(('_deleted_at__isnull', True)),
                fields=['_deleted_at'],
                name='release_deleted_at',
            ),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(
                condition=models.Q(('_deleted_at__isnull', True)),
                fields=['_deleted_at'],
                name='review_deleted_at',
            ),
        ),
        migrations.CreateModel(
            name='StadiumTour',
            fields=[
                (
                    'worldtour_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='testapp.worldtour',
                    ),
                ),
                ('capacity', models.IntegerField(default=0)),
            ],
            bases=('testapp.worldtour',),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(
                condition=models.Q(('_deleted_at__isnull', True)),
                fields=['_deleted_at'],
                name='tour_deleted_at',
            ),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(
                condition=models.Q(('_deleted_at__isnull', True)),
                fields=['_deleted_at'],
                name='track_deleted_at',
            ),
        ),
    ]
