# Generated by makeguitarmigrations command! [DIGEST:b8e3966299a189c9164de19e9e162667]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
    ]

    operations = [
        # Define function for MTI parent updated at triggers! [SQL:04170d74284c]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION set_parent_updated_at()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                EXECUTE format(
                    'UPDATE %I SET _updated_at = NOW() WHERE %I IN (SELECT %I FROM new_table);',
                    TG_ARGV[0], TG_ARGV[1], TG_ARGV[2]
                );
                RETURN NULL;
            END;
            $$
        """,
            reverse_sql="""
            DROP FUNCTION set_parent_updated_at();
        """,
        ),

    ]
