# Generated by makeguitarmigrations command! [DIGEST:aae75afe40da501ef976c121785dd8b2]

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0016_migrate_override_probe'),
    ]

    operations = [
        # Define function for MTI parent updated at triggers! [SQL:b0595735364a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION set_parent_updated_at()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF TG_NARGS = 3 THEN
                    EXECUTE format(
                        'UPDATE %I SET _updated_at = NOW() WHERE %I IN (SELECT %I FROM new_table);',
                        TG_ARGV[0], TG_ARGV[1], TG_ARGV[2]
                    );
                ELSIF TG_ARGV[0] = '' THEN
                    EXECUTE format(
                        'UPDATE %I SET _updated_at = NOW() WHERE %I IN (SELECT %I FROM new_table);',
                        TG_ARGV[1], TG_ARGV[2], TG_ARGV[3]
                    );
                ELSE
                    EXECUTE format(
                        'UPDATE %I.%I SET _updated_at = NOW() WHERE %I IN (SELECT %I FROM new_table);',
                        TG_ARGV[0], TG_ARGV[1], TG_ARGV[2], TG_ARGV[3]
                    );
                END IF;
                RETURN NULL;
            END;
            $$
        """,
            reverse_sql="""
            DROP FUNCTION set_parent_updated_at();
        """,
        ),
    ]
