# Generated by makeguitarmigrations command! [DIGEST:b24b237dc61a1aef437dbf2aa31b9e8a]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_auto_enforcement'),
    ]

    operations = [
        # Soft Delete Related Rule on "testapp_merch" that is related to "testapp_album"! [SQL:2c6a186e23cd]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete_related_testapp_merch
                AS ON UPDATE TO testapp_album
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE testapp_merch
                    SET _deleted_at = NOW()
                    WHERE bonus_album_id = old.id
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete_related_testapp_merch ON testapp_album;
        """,
        ),

    ]
