# Generated by makeguitarmigrations command! [DIGEST:2cb7f1461c5f9787831542bdf4c5d92c]

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0017_auto_enforcement_parent_trigger_function'),
    ]

    operations = [
        # Updated at Trigger on "testapp_genre" table! [SQL:f4d15e0cfa82]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_genre";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_genre" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_genre";
        """,
        ),
        # Updated at Trigger on "testapp_band" table! [SQL:f0d6088bfd7b]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_band";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_band" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_band";
        """,
        ),
        # Soft Delete Rule on "testapp_band" table! [SQL:3900e52ca49b]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_band"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_band"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_band";
        """,
        ),
        # Updated at Trigger on "testapp_album" table! [SQL:9e2218bfea6c]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_album";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_album" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_album";
        """,
        ),
        # Soft Delete Rule on "testapp_album" table! [SQL:e896977fb2a3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_album"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_album"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_album";
        """,
        ),
        # Updated at Trigger on "testapp_ensemble" table! [SQL:8df364a0a8a5]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_ensemble";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_ensemble" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_ensemble";
        """,
        ),
        # Soft Delete Rule on "testapp_ensemble" table! [SQL:0e24274e858a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_ensemble"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_ensemble"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_ensemble";
        """,
        ),
        # MTI Updated at Trigger on "testapp_orchestra" table (parent "testapp_ensemble")! [SQL:647e257e4342]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_orchestra";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_orchestra" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_parent_updated_at(
                    '', 'testapp_ensemble', 'id', 'ensemble_ptr_id'
                );
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_orchestra";
        """,
        ),
        # MTI Soft Delete Rule on "testapp_orchestra" table (parent "testapp_ensemble")! [SQL:9e6a9a5b5090]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_orchestra"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_ensemble"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."ensemble_ptr_id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_orchestra";
        """,
        ),
        # MTI Updated at Trigger on "testapp_chamberorchestra" table (parent "testapp_ensemble")! [SQL:18d938ace6bd]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_chamberorchestra";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_chamberorchestra" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_parent_updated_at(
                    '', 'testapp_ensemble', 'id', 'orchestra_ptr_id'
                );
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_chamberorchestra";
        """,
        ),
        # MTI Soft Delete Rule on "testapp_chamberorchestra" table (parent "testapp_ensemble")! [SQL:3102db623a73]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_chamberorchestra"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_ensemble"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."orchestra_ptr_id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_chamberorchestra";
        """,
        ),
        # Updated at Trigger on "testapp_merch" table! [SQL:12b4631440d9]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_merch";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_merch" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_merch";
        """,
        ),
        # Soft Delete Rule on "testapp_merch" table! [SQL:4efdc0033bc3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_merch"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_merch"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_merch";
        """,
        ),
        # Updated at Trigger on "testapp_section" table! [SQL:809bde324773]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_section";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_section" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_section";
        """,
        ),
        # Soft Delete Rule on "testapp_section" table! [SQL:7e999f6107dd]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_section"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_section"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_section";
        """,
        ),
        # Updated at Trigger on "testapp_label" table! [SQL:41ef2c6b2f25]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_label";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_label" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_label";
        """,
        ),
        # Soft Delete Rule on "testapp_label" table! [SQL:05209f97f691]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_label"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_label"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_label";
        """,
        ),
        # Updated at Trigger on "testapp_release" table! [SQL:b7db2d99fc01]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_release";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_release" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_release";
        """,
        ),
        # Soft Delete Rule on "testapp_release" table! [SQL:193fddaffe2e]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_release"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_release"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_release";
        """,
        ),
        # Updated at Trigger on "testapp_track" table! [SQL:8786000661e8]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_track";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_track" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_track";
        """,
        ),
        # Soft Delete Rule on "testapp_track" table! [SQL:192284329667]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_track"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_track"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_track";
        """,
        ),
        # Updated at Trigger on "testapp_tour" table! [SQL:6093fe5474e0]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_tour";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_tour" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_tour";
        """,
        ),
        # Soft Delete Rule on "testapp_tour" table! [SQL:4aa16b0c80cc]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_tour"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_tour"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_tour";
        """,
        ),
        # MTI Updated at Trigger on "testapp_worldtour" table (parent "testapp_tour")! [SQL:212b1b775100]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_worldtour";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_worldtour" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_parent_updated_at(
                    '', 'testapp_tour', 'id', 'tour_ptr_id'
                );
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_worldtour";
        """,
        ),
        # MTI Soft Delete Rule on "testapp_worldtour" table (parent "testapp_tour")! [SQL:a565f8000147]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_worldtour"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_tour"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."tour_ptr_id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_worldtour";
        """,
        ),
        # MTI Updated at Trigger on "testapp_stadiumtour" table (parent "testapp_tour")! [SQL:67e14e34404f]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_stadiumtour";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_stadiumtour" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_parent_updated_at(
                    '', 'testapp_tour', 'id', 'worldtour_ptr_id'
                );
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_stadiumtour";
        """,
        ),
        # MTI Soft Delete Rule on "testapp_stadiumtour" table (parent "testapp_tour")! [SQL:24be257be2b0]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_stadiumtour"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_tour"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."worldtour_ptr_id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_stadiumtour";
        """,
        ),
        # Updated at Trigger on "testapp_booking" table! [SQL:6c76bfbc57d6]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_booking";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_booking" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_booking";
        """,
        ),
        # Soft Delete Rule on "testapp_booking" table! [SQL:033eea2a49e7]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_booking"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_booking"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_booking";
        """,
        ),
        # Updated at Trigger on "testapp_review" table! [SQL:35bbebca9218]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_review";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_review" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_review";
        """,
        ),
        # Soft Delete Rule on "testapp_review" table! [SQL:f92f2a19c7db]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_review"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_review"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_review";
        """,
        ),
        # Updated at Trigger on "testapp_festival" table! [SQL:113337346a5c]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_festival";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_festival" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_festival";
        """,
        ),
        # Soft Delete Rule on "testapp_festival" table! [SQL:408dfaf22ec6]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_festival"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_festival"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_festival";
        """,
        ),
        # MTI Updated at Trigger on "testapp_touringfestival" table (parent "testapp_festival")! [SQL:a1456630eb0d]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_touringfestival";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_touringfestival" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_parent_updated_at(
                    '', 'testapp_festival', 'id', 'festival_ptr_id'
                );
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_touringfestival";
        """,
        ),
        # MTI Soft Delete Rule on "testapp_touringfestival" table (parent "testapp_festival")! [SQL:8346b09574fd]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_touringfestival"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_festival"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."festival_ptr_id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_touringfestival";
        """,
        ),
        # MTI Updated at Trigger on "testapp_headlinefestival" table (parent "testapp_festival")! [SQL:09fcf4e891ed]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_headlinefestival";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_headlinefestival" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_parent_updated_at(
                    '', 'testapp_festival', 'id', 'touringfestival_ptr_id'
                );
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_headlinefestival";
        """,
        ),
        # MTI Soft Delete Rule on "testapp_headlinefestival" table (parent "testapp_festival")! [SQL:6ef4c126bede]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_headlinefestival"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_festival"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."touringfestival_ptr_id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_headlinefestival";
        """,
        ),
        # Soft Delete Related Rule on "testapp_album" that is related to "testapp_band"! [SQL:2e1538d84c89]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_album"
                AS ON UPDATE TO "testapp_band"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_album"
                    SET _deleted_at = NOW()
                    WHERE "band_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_album" ON "testapp_band";
        """,
        ),
        # Soft Delete Related Rule on "testapp_merch" that is related to "testapp_album"! [SQL:c9514e3f24c7]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_merch"
                AS ON UPDATE TO "testapp_album"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_merch"
                    SET _deleted_at = NOW()
                    WHERE "album_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_merch" ON "testapp_album";
        """,
        ),
        # Soft Delete Related Rule on "testapp_merch" that is related to "testapp_album" via "bonus_album_id"! [SQL:d40d6a31bb7a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_merch_bonus_album_id"
                AS ON UPDATE TO "testapp_album"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_merch"
                    SET _deleted_at = NOW()
                    WHERE "bonus_album_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_merch_bonus_album_id" ON "testapp_album";
        """,
        ),
        # Soft Delete Related Rule on "testapp_section" that is related to "testapp_ensemble"! [SQL:d56c41464982]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_section"
                AS ON UPDATE TO "testapp_ensemble"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_section"
                    SET _deleted_at = NOW()
                    WHERE "orchestra_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_section" ON "testapp_ensemble";
        """,
        ),
        # Soft Delete Related Rule on "testapp_booking" that is related to "testapp_label"! [SQL:25ef973418d7]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_booking"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_booking"
                    SET _deleted_at = NOW()
                    WHERE "label_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_booking" ON "testapp_label";
        """,
        ),
        # Soft Delete Related Rule on "testapp_festival" that is related to "testapp_label"! [SQL:a16fc94035a3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_festival"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_festival"
                    SET _deleted_at = NOW()
                    WHERE "market_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_festival" ON "testapp_label";
        """,
        ),
        # Soft Delete Related Rule on "testapp_release" that is related to "testapp_label"! [SQL:46dfc759d28a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_release"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_release"
                    SET _deleted_at = NOW()
                    WHERE "label_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_release" ON "testapp_label";
        """,
        ),
        # Soft Delete Related Rule on "testapp_tour" that is related to "testapp_label"! [SQL:58ea084ca036]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_tour"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_tour"
                    SET _deleted_at = NOW()
                    WHERE "label_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_tour" ON "testapp_label";
        """,
        ),
        # Soft Delete Related Rule on "testapp_track" that is related to "testapp_label"! [SQL:fece89702127]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_track"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_track"
                    SET _deleted_at = NOW()
                    WHERE "label_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_track" ON "testapp_label";
        """,
        ),
        # Soft Delete Related Rule on "testapp_review" that is related to "testapp_release"! [SQL:ccbd9da8f5c1]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_review"
                AS ON UPDATE TO "testapp_release"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_review"
                    SET _deleted_at = NOW()
                    WHERE "release_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_review" ON "testapp_release";
        """,
        ),
        # Soft Delete Related Rule on "testapp_track" that is related to "testapp_release"! [SQL:80ff82e491c5]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_track"
                AS ON UPDATE TO "testapp_release"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_track"
                    SET _deleted_at = NOW()
                    WHERE "release_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_track" ON "testapp_release";
        """,
        ),
    ]
