# Generated by makeguitarmigrations command! [DIGEST:9210280d8ff27d10639c5e22ba5a629d]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_auto_enforcement_guitars_fill_5_label_label_id'),
    ]

    operations = [
        # Tenant autofill Trigger on "testapp_release" table (function "guitars_fill_5_label_label_id")! [SQL:938b0ccec75a]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER tenant_autofill_trigger
                BEFORE INSERT ON "testapp_release"
                FOR EACH ROW
                EXECUTE FUNCTION "guitars_fill_5_label_label_id"();
        """,
            reverse_sql="""
            DROP TRIGGER tenant_autofill_trigger ON "testapp_release";
        """,
        ),

        # Tenant autofill Trigger on "testapp_tour" table (function "guitars_fill_5_label_label_id")! [SQL:f6822998e1bf]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER tenant_autofill_trigger
                BEFORE INSERT ON "testapp_tour"
                FOR EACH ROW
                EXECUTE FUNCTION "guitars_fill_5_label_label_id"();
        """,
            reverse_sql="""
            DROP TRIGGER tenant_autofill_trigger ON "testapp_tour";
        """,
        ),

        # Tenant autofill Trigger on "testapp_track" table (function "guitars_fill_5_label_label_id")! [SQL:6d42980ec882]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER tenant_autofill_trigger
                BEFORE INSERT ON "testapp_track"
                FOR EACH ROW
                EXECUTE FUNCTION "guitars_fill_5_label_label_id"();
        """,
            reverse_sql="""
            DROP TRIGGER tenant_autofill_trigger ON "testapp_track";
        """,
        ),

    ]
