# Generated by makeguitarmigrations command! [DIGEST:275c4c36c79211d7a72b7634d93c03ab]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_auto_enforcement_guitars_fill_5_label_label_id'),
    ]

    operations = [
        # Tenant autofill Trigger on "testapp_release" table (function "guitars_fill_5_label_label_id")! [SQL:7f59cb3af917]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER "guitars_fill_5_label_label_id_trigger"
                BEFORE INSERT ON "testapp_release"
                FOR EACH ROW
                EXECUTE FUNCTION "guitars_fill_5_label_label_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "guitars_fill_5_label_label_id_trigger" ON "testapp_release";
        """,
        ),

        # Tenant autofill Trigger on "testapp_tour" table (function "guitars_fill_5_label_label_id")! [SQL:7b4a5f612c46]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER "guitars_fill_5_label_label_id_trigger"
                BEFORE INSERT ON "testapp_tour"
                FOR EACH ROW
                EXECUTE FUNCTION "guitars_fill_5_label_label_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "guitars_fill_5_label_label_id_trigger" ON "testapp_tour";
        """,
        ),

        # Tenant autofill Trigger on "testapp_track" table (function "guitars_fill_5_label_label_id")! [SQL:683553fd1e15]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER "guitars_fill_5_label_label_id_trigger"
                BEFORE INSERT ON "testapp_track"
                FOR EACH ROW
                EXECUTE FUNCTION "guitars_fill_5_label_label_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "guitars_fill_5_label_label_id_trigger" ON "testapp_track";
        """,
        ),

    ]
