# Generated by Django 5.2.15 on 2026-08-16 14:41

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_auto_enforcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='testapp.label')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='testapp.label')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='testapp.label')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('venue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.venue')),
                ('seats', models.IntegerField(default=0)),
            ],
            bases=('testapp.venue',),
        ),
        migrations.CreateModel(
            name='ConcertHall',
            fields=[
                ('hall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.hall')),
                ('stage', models.CharField(default='', max_length=50)),
            ],
            bases=('testapp.hall',),
        ),
        migrations.CreateModel(
            name='LectureHall',
            fields=[
                ('hall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.hall')),
                ('rows', models.IntegerField(default=0)),
            ],
            bases=('testapp.hall',),
        ),
        migrations.CreateModel(
            name='SquashCourt',
            fields=[
                ('court_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.court')),
                ('walls', models.IntegerField(default=4)),
            ],
            bases=('testapp.court',),
        ),
        migrations.CreateModel(
            name='TennisCourt',
            fields=[
                ('court_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.court')),
                ('net_height', models.IntegerField(default=0)),
            ],
            bases=('testapp.court',),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(condition=models.Q(('_deleted_at__isnull', True)), fields=['_deleted_at'], name='venue_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(condition=models.Q(('_deleted_at__isnull', True)), fields=['_deleted_at'], name='hall_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(condition=models.Q(('_deleted_at__isnull', True)), fields=['_deleted_at'], name='court_deleted_at'),
        ),
    ]
