# Generated by makeguitarmigrations command! [DIGEST:f1710af52b4e8e69a4de0774efd28bd4]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0025_patron'),
    ]

    operations = [
        # Updated at Trigger on "testapp_patron" table! [SQL:f15a2ba7ba52]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_patron" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_patron";
        """,
        ),

        # Soft Delete Rule on "testapp_patron" table! [SQL:40420f7e7728]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_patron"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_patron"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_patron";
        """,
        ),

        # Soft Delete Owned Rule on "testapp_ensemble" that is owned by "testapp_patron" via "ensemble_id"! [SQL:4bc49c2d411d]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_testapp_ensemble_ensemble_id"
                AS ON UPDATE TO "testapp_patron"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_ensemble"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."ensemble_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_patron" AS guitars_owner
                          WHERE guitars_owner."ensemble_id" = old."ensemble_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_testapp_ensemble_ensemble_id" ON "testapp_patron";
        """,
        ),

    ]
