# Generated by makeguitarmigrations command! [DIGEST:f7a8644f53bd2afb26bfb2cc6c0ff220]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0027_stagehand_rider_residency_rider_rider_deleted_at'),
    ]

    operations = [
        # Updated at Trigger on "testapp_stagehand" table! [SQL:dce0b3c9a62d]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_stagehand" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_stagehand";
        """,
        ),

        # Soft Delete Rule on "testapp_stagehand" table! [SQL:993bf12b53f1]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_stagehand"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_stagehand"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_stagehand";
        """,
        ),

        # Updated at Trigger on "testapp_rider" table! [SQL:fab05b626783]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_rider" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_rider";
        """,
        ),

        # Soft Delete Rule on "testapp_rider" table! [SQL:30746cebb0e4]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_rider"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_rider"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_rider";
        """,
        ),

        # Updated at Trigger on "testapp_residency" table! [SQL:0e53a3388893]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_residency" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_residency";
        """,
        ),

        # Soft Delete Rule on "testapp_residency" table! [SQL:cde84c5ac431]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_residency"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_residency"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_residency";
        """,
        ),

        # Soft Delete Owned Rule on "testapp_stagehand" that is owned by "testapp_rider" via "stagehand_id"! [SQL:b521a9b1c045]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_17_testapp_stagehand_12_stagehand_id"
                AS ON UPDATE TO "testapp_rider"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_stagehand"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."stagehand_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_rider" AS guitars_owner
                          WHERE guitars_owner."stagehand_id" = old."stagehand_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_17_testapp_stagehand_12_stagehand_id" ON "testapp_rider";
        """,
        ),

        # Soft Delete Owned Rule on "testapp_rider" that is owned by "testapp_residency" via "rider_id"! [SQL:e228c15ca712]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_13_testapp_rider_8_rider_id"
                AS ON UPDATE TO "testapp_residency"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_rider"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."rider_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_residency" AS guitars_owner
                          WHERE guitars_owner."rider_id" = old."rider_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_13_testapp_rider_8_rider_id" ON "testapp_residency";
        """,
        ),

    ]
