# Generated by Django 5.2.15 on 2026-08-21 17:56

import django.db.models.deletion
import guitars.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_auto_enforcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='placard',
            name='parent',
            field=guitars.models.OwningForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='testapp.placard'),
        ),
    ]
