# Generated by makeguitarmigrations command! [DIGEST:22003d269b086dbe22c100ead42c465f]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_ensemble_press_kit'),
    ]

    operations = [
        # Soft Delete Owned Rule on "testapp_presskit" that is owned by "testapp_album" via "alt_press_kit_id"! [SQL:ea3cd7698242]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_16_testapp_presskit_16_alt_press_kit_id"
                AS ON UPDATE TO "testapp_album"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_presskit"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."alt_press_kit_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner
                          WHERE guitars_owner."alt_press_kit_id" = old."alt_press_kit_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner_1
                          WHERE guitars_owner_1."press_kit_id" = old."alt_press_kit_id"
                            AND guitars_owner_1."id" <> old."id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_ensemble" AS guitars_owner_2
                          WHERE guitars_owner_2."press_kit_id" = old."alt_press_kit_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_orchestra" AS guitars_owner_3
                          JOIN "testapp_ensemble" AS guitars_owner_3_root
                              ON guitars_owner_3_root."id" = guitars_owner_3."ensemble_ptr_id"
                          WHERE guitars_owner_3."programme_id" = old."alt_press_kit_id"
                            AND guitars_owner_3_root._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_16_testapp_presskit_16_alt_press_kit_id" ON "testapp_album";
        """,
        ),

        # Soft Delete Owned Rule on "testapp_presskit" that is owned by "testapp_album" via "press_kit_id"! [SQL:f8931191a8a1]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_16_testapp_presskit_12_press_kit_id"
                AS ON UPDATE TO "testapp_album"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_presskit"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."press_kit_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner
                          WHERE guitars_owner."press_kit_id" = old."press_kit_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner_1
                          WHERE guitars_owner_1."alt_press_kit_id" = old."press_kit_id"
                            AND guitars_owner_1."id" <> old."id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_ensemble" AS guitars_owner_2
                          WHERE guitars_owner_2."press_kit_id" = old."press_kit_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_orchestra" AS guitars_owner_3
                          JOIN "testapp_ensemble" AS guitars_owner_3_root
                              ON guitars_owner_3_root."id" = guitars_owner_3."ensemble_ptr_id"
                          WHERE guitars_owner_3."programme_id" = old."press_kit_id"
                            AND guitars_owner_3_root._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_16_testapp_presskit_12_press_kit_id" ON "testapp_album";
        """,
        ),

        # Soft Delete Owned Rule on "testapp_presskit" that is owned by "testapp_ensemble" via "press_kit_id"! [SQL:232d93fb93d7]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_16_testapp_presskit_12_press_kit_id"
                AS ON UPDATE TO "testapp_ensemble"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_presskit"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."press_kit_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_ensemble" AS guitars_owner
                          WHERE guitars_owner."press_kit_id" = old."press_kit_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner_1
                          WHERE guitars_owner_1."alt_press_kit_id" = old."press_kit_id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner_2
                          WHERE guitars_owner_2."press_kit_id" = old."press_kit_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_orchestra" AS guitars_owner_3
                          JOIN "testapp_ensemble" AS guitars_owner_3_root
                              ON guitars_owner_3_root."id" = guitars_owner_3."ensemble_ptr_id"
                          WHERE guitars_owner_3."programme_id" = old."press_kit_id"
                            AND guitars_owner_3_root."id" <> old."id"
                            AND guitars_owner_3_root._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_16_testapp_presskit_12_press_kit_id" ON "testapp_ensemble";
        """,
        ),

    ]
