# Generated by makeguitarmigrations command! [DIGEST:9817b503ecc7a73ad2a467435c29291a]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0037_auto_enforcement'),
    ]

    operations = [
        # Soft Delete Owned Sweep on "testapp_presskit" that is owned by "testapp_album" via "alt_press_kit_id"! [SQL:ed4e994ce65e]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_13_testapp_album_16_testapp__c9e1014f18"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_presskit" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_after.*
                        FROM guitars_owned_after AS guitars_after
                        JOIN guitars_owned_before AS guitars_before
                            ON guitars_before."id" = guitars_after."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_after."alt_press_kit_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."alt_press_kit_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner
                          WHERE guitars_owner."alt_press_kit_id" = guitars_archived."alt_press_kit_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner_1
                          WHERE guitars_owner_1."press_kit_id" = guitars_archived."alt_press_kit_id"
                            AND guitars_owner_1."id" <> guitars_archived."id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_ensemble" AS guitars_owner_2
                          WHERE guitars_owner_2."press_kit_id" = guitars_archived."alt_press_kit_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_orchestra" AS guitars_owner_3
                          JOIN "testapp_ensemble" AS guitars_owner_3_root
                              ON guitars_owner_3_root."id" = guitars_owner_3."ensemble_ptr_id"
                          WHERE guitars_owner_3."programme_id" = guitars_archived."alt_press_kit_id"
                            AND guitars_owner_3_root._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_13_testapp_album_16_testapp__c9e1014f18"
                AFTER UPDATE ON "testapp_album"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_13_testapp_album_16_testapp__c9e1014f18"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_13_testapp_album_16_testapp__c9e1014f18" ON "testapp_album";

            DROP FUNCTION "soft_delete_owned_sweep_13_testapp_album_16_testapp__c9e1014f18"();
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_presskit" that is owned by "testapp_album" via "press_kit_id"! [SQL:8aa4200fd0e8]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_13_testapp_album_16_testapp__334bdb7a77"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_presskit" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_after.*
                        FROM guitars_owned_after AS guitars_after
                        JOIN guitars_owned_before AS guitars_before
                            ON guitars_before."id" = guitars_after."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_after."press_kit_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."press_kit_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner
                          WHERE guitars_owner."press_kit_id" = guitars_archived."press_kit_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner_1
                          WHERE guitars_owner_1."alt_press_kit_id" = guitars_archived."press_kit_id"
                            AND guitars_owner_1."id" <> guitars_archived."id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_ensemble" AS guitars_owner_2
                          WHERE guitars_owner_2."press_kit_id" = guitars_archived."press_kit_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_orchestra" AS guitars_owner_3
                          JOIN "testapp_ensemble" AS guitars_owner_3_root
                              ON guitars_owner_3_root."id" = guitars_owner_3."ensemble_ptr_id"
                          WHERE guitars_owner_3."programme_id" = guitars_archived."press_kit_id"
                            AND guitars_owner_3_root._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_13_testapp_album_16_testapp__334bdb7a77"
                AFTER UPDATE ON "testapp_album"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_13_testapp_album_16_testapp__334bdb7a77"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_13_testapp_album_16_testapp__334bdb7a77" ON "testapp_album";

            DROP FUNCTION "soft_delete_owned_sweep_13_testapp_album_16_testapp__334bdb7a77"();
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_presskit" that is owned by "testapp_ensemble" via "press_kit_id"! [SQL:4adc1f00a420]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_16_testapp_ensemble_16_testa_a783e60c61"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_presskit" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_after.*
                        FROM guitars_owned_after AS guitars_after
                        JOIN guitars_owned_before AS guitars_before
                            ON guitars_before."id" = guitars_after."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_after."press_kit_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."press_kit_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_ensemble" AS guitars_owner
                          WHERE guitars_owner."press_kit_id" = guitars_archived."press_kit_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner_1
                          WHERE guitars_owner_1."alt_press_kit_id" = guitars_archived."press_kit_id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_album" AS guitars_owner_2
                          WHERE guitars_owner_2."press_kit_id" = guitars_archived."press_kit_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_orchestra" AS guitars_owner_3
                          JOIN "testapp_ensemble" AS guitars_owner_3_root
                              ON guitars_owner_3_root."id" = guitars_owner_3."ensemble_ptr_id"
                          WHERE guitars_owner_3."programme_id" = guitars_archived."press_kit_id"
                            AND guitars_owner_3_root."id" <> guitars_archived."id"
                            AND guitars_owner_3_root._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_16_testapp_ensemble_16_testa_a783e60c61"
                AFTER UPDATE ON "testapp_ensemble"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_16_testapp_ensemble_16_testa_a783e60c61"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_16_testapp_ensemble_16_testa_a783e60c61" ON "testapp_ensemble";

            DROP FUNCTION "soft_delete_owned_sweep_16_testapp_ensemble_16_testa_a783e60c61"();
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_ensemble" that is owned by "testapp_merch" via "featured_orchestra_id"! [SQL:094d3376b1e4]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_13_testapp_merch_16_testapp__a2efbfd03b"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_ensemble" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_after.*
                        FROM guitars_owned_after AS guitars_after
                        JOIN guitars_owned_before AS guitars_before
                            ON guitars_before."id" = guitars_after."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_after."featured_orchestra_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."featured_orchestra_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_merch" AS guitars_owner
                          WHERE guitars_owner."featured_orchestra_id" = guitars_archived."featured_orchestra_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_patron" AS guitars_owner_1
                          WHERE guitars_owner_1."ensemble_id" = guitars_archived."featured_orchestra_id"
                            AND guitars_owner_1._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_13_testapp_merch_16_testapp__a2efbfd03b"
                AFTER UPDATE ON "testapp_merch"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_13_testapp_merch_16_testapp__a2efbfd03b"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_13_testapp_merch_16_testapp__a2efbfd03b" ON "testapp_merch";

            DROP FUNCTION "soft_delete_owned_sweep_13_testapp_merch_16_testapp__a2efbfd03b"();
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_ensemble" that is owned by "testapp_patron" via "ensemble_id"! [SQL:8c472cdafff9]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_14_testapp_patron_16_testapp_f691a7bc95"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_ensemble" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_after.*
                        FROM guitars_owned_after AS guitars_after
                        JOIN guitars_owned_before AS guitars_before
                            ON guitars_before."id" = guitars_after."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_after."ensemble_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."ensemble_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_patron" AS guitars_owner
                          WHERE guitars_owner."ensemble_id" = guitars_archived."ensemble_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_merch" AS guitars_owner_1
                          WHERE guitars_owner_1."featured_orchestra_id" = guitars_archived."ensemble_id"
                            AND guitars_owner_1._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_14_testapp_patron_16_testapp_f691a7bc95"
                AFTER UPDATE ON "testapp_patron"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_14_testapp_patron_16_testapp_f691a7bc95"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_14_testapp_patron_16_testapp_f691a7bc95" ON "testapp_patron";

            DROP FUNCTION "soft_delete_owned_sweep_14_testapp_patron_16_testapp_f691a7bc95"();
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_stagehand" that is owned by "testapp_rider" via "stagehand_id"! [SQL:370b3a659331]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_13_testapp_rider_17_testapp__5d4408f760"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_stagehand" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_after.*
                        FROM guitars_owned_after AS guitars_after
                        JOIN guitars_owned_before AS guitars_before
                            ON guitars_before."id" = guitars_after."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_after."stagehand_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."stagehand_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_rider" AS guitars_owner
                          WHERE guitars_owner."stagehand_id" = guitars_archived."stagehand_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_13_testapp_rider_17_testapp__5d4408f760"
                AFTER UPDATE ON "testapp_rider"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_13_testapp_rider_17_testapp__5d4408f760"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_13_testapp_rider_17_testapp__5d4408f760" ON "testapp_rider";

            DROP FUNCTION "soft_delete_owned_sweep_13_testapp_rider_17_testapp__5d4408f760"();
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_rider" that is owned by "testapp_residency" via "rider_id"! [SQL:edee9fa10d70]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_17_testapp_residency_13_test_daabc7e451"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_rider" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_after.*
                        FROM guitars_owned_after AS guitars_after
                        JOIN guitars_owned_before AS guitars_before
                            ON guitars_before."id" = guitars_after."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_after."rider_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."rider_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_residency" AS guitars_owner
                          WHERE guitars_owner."rider_id" = guitars_archived."rider_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_17_testapp_residency_13_test_daabc7e451"
                AFTER UPDATE ON "testapp_residency"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_17_testapp_residency_13_test_daabc7e451"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_17_testapp_residency_13_test_daabc7e451" ON "testapp_residency";

            DROP FUNCTION "soft_delete_owned_sweep_17_testapp_residency_13_test_daabc7e451"();
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_placard" that is owned by "testapp_kiosk" via "placard_id"! [SQL:1f0a8576f50d]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_13_testapp_kiosk_15_testapp__6599948231"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_placard" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_after.*
                        FROM guitars_owned_after AS guitars_after
                        JOIN guitars_owned_before AS guitars_before
                            ON guitars_before."id" = guitars_after."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_after."placard_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."placard_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_kiosk" AS guitars_owner
                          WHERE guitars_owner."placard_id" = guitars_archived."placard_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_foyer" AS guitars_owner_1
                          WHERE guitars_owner_1."placard_id" = guitars_archived."placard_id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_placard" AS guitars_owner_2
                          WHERE guitars_owner_2."parent_id" = guitars_archived."placard_id"
                            AND guitars_owner_2."id" <> guitars_archived."placard_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_spotlitplacard" AS guitars_owner_3
                          JOIN "testapp_placard" AS guitars_owner_3_root
                              ON guitars_owner_3_root."id" = guitars_owner_3."placard_ptr_id"
                          WHERE guitars_owner_3."pin_id" = guitars_archived."placard_id"
                            AND guitars_owner_3_root."id" <> guitars_archived."placard_id"
                            AND guitars_owner_3_root._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_13_testapp_kiosk_15_testapp__6599948231"
                AFTER UPDATE ON "testapp_kiosk"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_13_testapp_kiosk_15_testapp__6599948231"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_13_testapp_kiosk_15_testapp__6599948231" ON "testapp_kiosk";

            DROP FUNCTION "soft_delete_owned_sweep_13_testapp_kiosk_15_testapp__6599948231"();
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_placard" that is owned by "testapp_foyer" via "placard_id"! [SQL:606f1460b12d]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_13_testapp_foyer_15_testapp__951604b7d8"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_placard" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_after.*
                        FROM guitars_owned_after AS guitars_after
                        JOIN guitars_owned_before AS guitars_before
                            ON guitars_before."id" = guitars_after."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_after."placard_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."placard_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_foyer" AS guitars_owner
                          WHERE guitars_owner."placard_id" = guitars_archived."placard_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_kiosk" AS guitars_owner_1
                          WHERE guitars_owner_1."placard_id" = guitars_archived."placard_id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_placard" AS guitars_owner_2
                          WHERE guitars_owner_2."parent_id" = guitars_archived."placard_id"
                            AND guitars_owner_2."id" <> guitars_archived."placard_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_spotlitplacard" AS guitars_owner_3
                          JOIN "testapp_placard" AS guitars_owner_3_root
                              ON guitars_owner_3_root."id" = guitars_owner_3."placard_ptr_id"
                          WHERE guitars_owner_3."pin_id" = guitars_archived."placard_id"
                            AND guitars_owner_3_root."id" <> guitars_archived."placard_id"
                            AND guitars_owner_3_root._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_13_testapp_foyer_15_testapp__951604b7d8"
                AFTER UPDATE ON "testapp_foyer"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_13_testapp_foyer_15_testapp__951604b7d8"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_13_testapp_foyer_15_testapp__951604b7d8" ON "testapp_foyer";

            DROP FUNCTION "soft_delete_owned_sweep_13_testapp_foyer_15_testapp__951604b7d8"();
        """,
        ),

    ]
