# Generated by makeguitarmigrations command! [DIGEST:50d1a66c9f5eade4cae09a497e6c494a]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0039_awning_banner_billboard_scribble_signboard_and_more'),
    ]

    operations = [
        # Updated at Trigger on "testapp_awning" table! [SQL:03ffd009c427]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_awning" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_awning";
        """,
        ),

        # Soft Delete Rule on "testapp_awning" table! [SQL:264692f9edcf]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_awning"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_awning"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_awning";
        """,
        ),

        # Updated at Trigger on "testapp_banner" table! [SQL:e116a12bbfa0]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_banner" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_banner";
        """,
        ),

        # Soft Delete Rule on "testapp_banner" table! [SQL:e1beeae1b3a2]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_banner"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_banner"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_banner";
        """,
        ),

        # Updated at Trigger on "testapp_billboard" table! [SQL:0240dbf558ea]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_billboard" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_billboard";
        """,
        ),

        # Soft Delete Rule on "testapp_billboard" table! [SQL:130e7c5b44d5]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_billboard"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_billboard"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_billboard";
        """,
        ),

        # Updated at Trigger on "testapp_signboard" table! [SQL:0da941035dca]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_signboard" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_signboard";
        """,
        ),

        # Soft Delete Rule on "testapp_signboard" table! [SQL:ce96dc98a6eb]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_signboard"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_signboard"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_signboard";
        """,
        ),

        # Updated at Trigger on "testapp_scribble" table! [SQL:cb4c74c17327]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_scribble" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_scribble";
        """,
        ),

        # Soft Delete Rule on "testapp_scribble" table! [SQL:c809b51eb99c]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_scribble"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_scribble"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_scribble";
        """,
        ),

        # Soft Delete Owned Rule on "testapp_awning" that is owned by "testapp_banner" via "awning_id"! [SQL:3d8f6cabf011]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_14_testapp_awning_9_awning_id"
                AS ON UPDATE TO "testapp_banner"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_awning"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."awning_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_banner" AS guitars_owner
                          WHERE guitars_owner."awning_id" = old."awning_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_14_testapp_awning_9_awning_id" ON "testapp_banner";
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_awning" that is owned by "testapp_banner" via "awning_id"! [SQL:f929e54d6c0e]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_14_testapp_banner_14_testapp_f417b53ba1"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_owned_before AS guitars_before
                        JOIN "testapp_awning" AS guitars_dependent
                            ON guitars_dependent."id" = guitars_before."awning_id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_before."awning_id" IS NOT NULL
                          AND guitars_dependent._deleted_at IS NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_owned_after AS guitars_after
                              WHERE guitars_after."id" = guitars_before."id"
                          )
                          AND NOT EXISTS (
                              SELECT 1 FROM "testapp_banner" AS guitars_owner
                              WHERE guitars_owner."awning_id" = guitars_before."awning_id"
                                AND guitars_owner._deleted_at IS NULL
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % rewrote the primary key of a live owning row '
                            'whose dependent is now held by no live owner. The owned sweep correlates '
                            'its transition tables on the primary key, so it cannot tell whether that '
                            'row was archived, and would leak the dependent permanently. Rewrite the '
                            'key and archive the row in separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                    UPDATE "testapp_awning" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_owned_before AS guitars_before
                        JOIN guitars_owned_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_before."awning_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."awning_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_banner" AS guitars_owner
                          WHERE guitars_owner."awning_id" = guitars_archived."awning_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_14_testapp_banner_14_testapp_f417b53ba1"
                AFTER UPDATE ON "testapp_banner"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_14_testapp_banner_14_testapp_f417b53ba1"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_14_testapp_banner_14_testapp_f417b53ba1" ON "testapp_banner";

            DROP FUNCTION "soft_delete_owned_sweep_14_testapp_banner_14_testapp_f417b53ba1"();
        """,
        ),

        # Soft Delete Owned Rule on "testapp_banner" that is owned by "testapp_billboard" via "banner_id"! [SQL:0a56a8ae54f4]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_14_testapp_banner_9_banner_id"
                AS ON UPDATE TO "testapp_billboard"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_banner"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."banner_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_billboard" AS guitars_owner
                          WHERE guitars_owner."banner_id" = old."banner_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_14_testapp_banner_9_banner_id" ON "testapp_billboard";
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_banner" that is owned by "testapp_billboard" via "banner_id"! [SQL:c5db3e1130df]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_17_testapp_billboard_14_test_d5220b4a6b"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_owned_before AS guitars_before
                        JOIN "testapp_banner" AS guitars_dependent
                            ON guitars_dependent."id" = guitars_before."banner_id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_before."banner_id" IS NOT NULL
                          AND guitars_dependent._deleted_at IS NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_owned_after AS guitars_after
                              WHERE guitars_after."id" = guitars_before."id"
                          )
                          AND NOT EXISTS (
                              SELECT 1 FROM "testapp_billboard" AS guitars_owner
                              WHERE guitars_owner."banner_id" = guitars_before."banner_id"
                                AND guitars_owner._deleted_at IS NULL
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % rewrote the primary key of a live owning row '
                            'whose dependent is now held by no live owner. The owned sweep correlates '
                            'its transition tables on the primary key, so it cannot tell whether that '
                            'row was archived, and would leak the dependent permanently. Rewrite the '
                            'key and archive the row in separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                    UPDATE "testapp_banner" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_owned_before AS guitars_before
                        JOIN guitars_owned_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_before."banner_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."banner_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_billboard" AS guitars_owner
                          WHERE guitars_owner."banner_id" = guitars_archived."banner_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_17_testapp_billboard_14_test_d5220b4a6b"
                AFTER UPDATE ON "testapp_billboard"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_17_testapp_billboard_14_test_d5220b4a6b"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_17_testapp_billboard_14_test_d5220b4a6b" ON "testapp_billboard";

            DROP FUNCTION "soft_delete_owned_sweep_17_testapp_billboard_14_test_d5220b4a6b"();
        """,
        ),

    ]
