# Generated by Django 5.2.15 on 2026-09-08 06:03

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0040_auto_enforcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='testapp.setlist',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='SetlistEntry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('song', models.CharField(max_length=100)),
                (
                    'setlist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entries',
                        to='testapp.setlist',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='setlist',
            index=models.Index(
                condition=models.Q(('_deleted_at__isnull', True)),
                fields=['_deleted_at'],
                name='setlist_deleted_at',
            ),
        ),
        migrations.AddIndex(
            model_name='setlistentry',
            index=models.Index(
                condition=models.Q(('_deleted_at__isnull', True)),
                fields=['_deleted_at'],
                name='setlistentry_deleted_at',
            ),
        ),
    ]
