# Generated by makeguitarmigrations command! [DIGEST:37e61a6fd64d6b42437862f72a0f45f3]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_auto_enforcement_guitars_fill_5_label_label_id'),
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0043_riser_rack_troupe'),
    ]

    operations = [
        # Updated at Trigger on "testapp_riser" table! [SQL:0c75f0a4173f]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_riser" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_riser";
        """,
        ),

        # Soft Delete Rule on "testapp_riser" table! [SQL:38350a4a5031]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_riser"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_riser"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_riser";
        """,
        ),

        # Updated at Trigger on "testapp_rack" table! [SQL:eb311a756b30]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_rack" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_rack";
        """,
        ),

        # Soft Delete Rule on "testapp_rack" table! [SQL:e50c51f7688a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_rack"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_rack"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_rack";
        """,
        ),

        # Updated at Trigger on "testapp_troupe" table! [SQL:b563a8d8d2fb]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_troupe" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_troupe";
        """,
        ),

        # Soft Delete Rule on "testapp_troupe" table! [SQL:f231cbc86173]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_troupe"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_troupe"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_troupe";
        """,
        ),

        # Soft Delete Related Rule on "testapp_troupe" that is related to "testapp_label"! [SQL:1c5e140e0e1d]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_troupe"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_troupe"
                    SET _deleted_at = NOW()
                    WHERE "label_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_troupe" ON "testapp_label";
        """,
        ),

        # Soft Delete Self Cascade Trigger on "testapp_rack" via "parent_id"! [SQL:4c4cbeab4d78]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_self_cascade_12_testapp_rack_9_parent_id"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                   AND EXISTS (
                       SELECT 1
                       FROM guitars_self_before AS guitars_before
                       JOIN guitars_self_after AS guitars_after
                           ON guitars_after."id" = guitars_before."id"
                       WHERE guitars_before._deleted_at IS NULL
                         AND guitars_after._deleted_at IS NOT NULL
                   ) THEN
                    UPDATE "testapp_rack" AS guitars_child
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before."id" AS guitars_key
                        FROM guitars_self_before AS guitars_before
                        JOIN guitars_self_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_child."parent_id" = guitars_archived.guitars_key
                      AND guitars_child._deleted_at IS NULL;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_self_cascade_12_testapp_rack_9_parent_id"
                AFTER UPDATE ON "testapp_rack"
                REFERENCING OLD TABLE AS guitars_self_before NEW TABLE AS guitars_self_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_self_cascade_12_testapp_rack_9_parent_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_self_cascade_12_testapp_rack_9_parent_id" ON "testapp_rack";

            DROP FUNCTION "soft_delete_self_cascade_12_testapp_rack_9_parent_id"();
        """,
        ),

        # Soft Delete Owned Rule on "testapp_riser" that is owned by "testapp_rack" via "riser_id"! [SQL:11529906492c]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_13_testapp_riser_8_riser_id"
                AS ON UPDATE TO "testapp_rack"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_riser"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."riser_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_rack" AS guitars_owner
                          WHERE guitars_owner."riser_id" = old."riser_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_13_testapp_riser_8_riser_id" ON "testapp_rack";
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_riser" that is owned by "testapp_rack" via "riser_id"! [SQL:7a9362d06bc9]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_12_testapp_rack_13_testapp_r_e10c5b7096"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_owned_before AS guitars_before
                        JOIN "testapp_riser" AS guitars_dependent
                            ON guitars_dependent."id" = guitars_before."riser_id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_before."riser_id" IS NOT NULL
                          AND guitars_dependent._deleted_at IS NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_owned_after AS guitars_after
                              WHERE guitars_after."id" = guitars_before."id"
                          )
                          AND NOT EXISTS (
                              SELECT 1 FROM "testapp_rack" AS guitars_owner
                              WHERE guitars_owner."riser_id" = guitars_before."riser_id"
                                AND guitars_owner._deleted_at IS NULL
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % rewrote the primary key of a live owning row '
                            'whose dependent is now held by no live owner. The owned sweep correlates '
                            'its transition tables on the primary key, so it cannot tell whether that '
                            'row was archived, and would leak the dependent permanently. Rewrite the '
                            'key and archive the row in separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                    UPDATE "testapp_riser" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_owned_before AS guitars_before
                        JOIN guitars_owned_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_before."riser_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."riser_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_rack" AS guitars_owner
                          WHERE guitars_owner."riser_id" = guitars_archived."riser_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_12_testapp_rack_13_testapp_r_e10c5b7096"
                AFTER UPDATE ON "testapp_rack"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_12_testapp_rack_13_testapp_r_e10c5b7096"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_12_testapp_rack_13_testapp_r_e10c5b7096" ON "testapp_rack";

            DROP FUNCTION "soft_delete_owned_sweep_12_testapp_rack_13_testapp_r_e10c5b7096"();
        """,
        ),

        # Soft Delete Self Cascade Trigger on "testapp_troupe" via "parent_id"! [SQL:ca1ffd4803ed]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_self_cascade_14_testapp_troupe_9_parent_id"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                   AND EXISTS (
                       SELECT 1
                       FROM guitars_self_before AS guitars_before
                       JOIN guitars_self_after AS guitars_after
                           ON guitars_after."id" = guitars_before."id"
                       WHERE guitars_before._deleted_at IS NULL
                         AND guitars_after._deleted_at IS NOT NULL
                   ) THEN
                    UPDATE "testapp_troupe" AS guitars_child
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before."id" AS guitars_key
                        FROM guitars_self_before AS guitars_before
                        JOIN guitars_self_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_child."parent_id" = guitars_archived.guitars_key
                      AND guitars_child._deleted_at IS NULL;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_self_cascade_14_testapp_troupe_9_parent_id"
                AFTER UPDATE ON "testapp_troupe"
                REFERENCING OLD TABLE AS guitars_self_before NEW TABLE AS guitars_self_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_self_cascade_14_testapp_troupe_9_parent_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_self_cascade_14_testapp_troupe_9_parent_id" ON "testapp_troupe";

            DROP FUNCTION "soft_delete_self_cascade_14_testapp_troupe_9_parent_id"();
        """,
        ),

        # Tenant autofill Trigger on "testapp_troupe" table (function "guitars_fill_5_label_label_id")! [SQL:fde02cf78302]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER "guitars_fill_5_label_label_id_trigger"
                BEFORE INSERT ON "testapp_troupe"
                FOR EACH ROW
                EXECUTE FUNCTION "guitars_fill_5_label_label_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "guitars_fill_5_label_label_id_trigger" ON "testapp_troupe";
        """,
        ),

        # Tenant RLS on "testapp_troupe" table! [POLICY:1669775c43fd] [SQL:db4aecf1c60b]
        migrations.RunSQL(
            sql=[
                """CREATE POLICY tenant_scope ON testapp_troupe FOR ALL TO PUBLIC
            USING ((SELECT current_setting('tenant.bypass', true)) = 'on' OR (testapp_troupe.label_id::text = ANY(string_to_array((SELECT current_setting('tenant.label', true)), ','))))
            WITH CHECK ((SELECT current_setting('tenant.bypass', true)) = 'on' OR (testapp_troupe.label_id::text = ANY(string_to_array((SELECT current_setting('tenant.label', true)), ','))))""",
                """ALTER TABLE testapp_troupe ENABLE ROW LEVEL SECURITY""",
                """ALTER TABLE testapp_troupe FORCE ROW LEVEL SECURITY""",
            ],
            reverse_sql=[
                """ALTER TABLE testapp_troupe NO FORCE ROW LEVEL SECURITY""",
                """ALTER TABLE testapp_troupe DISABLE ROW LEVEL SECURITY""",
                """DROP POLICY IF EXISTS tenant_scope ON testapp_troupe""",
            ],
        ),

    ]
