# Generated by makeguitarmigrations command! [DIGEST:79468cd328559f0558c3e68266d584dc]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0045_auto_enforcement'),
    ]

    operations = [
        # Soft Delete Self Cascade Trigger on "testapp_setlist" via "parent_id"! [SQL:d2b33851de6e]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER "soft_delete_self_cascade_15_testapp_setlist_9_parent_id" ON "testapp_setlist";

            CREATE OR REPLACE FUNCTION "soft_delete_self_cascade_15_testapp_setlist_9_parent_id"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_self_after AS guitars_after
                        WHERE guitars_after._deleted_at IS NOT NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_self_before AS guitars_before
                              WHERE guitars_before."id" = guitars_after."id"
                          )
                          AND EXISTS (
                              SELECT 1 FROM "testapp_setlist" AS guitars_child
                              WHERE guitars_child._deleted_at IS NULL
                                AND (
                                    guitars_child."parent_id" = guitars_after."id"
                                    OR guitars_child."parent_id" IN (
                                        SELECT guitars_vanished."id"
                                        FROM guitars_self_before AS guitars_vanished
                                        WHERE guitars_vanished._deleted_at IS NULL
                                          AND NOT EXISTS (
                                              SELECT 1 FROM guitars_self_after AS guitars_kept
                                              WHERE guitars_kept."id"
                                                  = guitars_vanished."id"
                                          )
                                    )
                                )
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % archived a row whose primary key it also '
                            'rewrote, and a live child is left holding one of the two keys. The self '
                            'cascade trigger correlates its transition tables on the primary key, so '
                            'it cannot tell which before-row that archived row was, and would leak the '
                            'whole subtree permanently. Rewrite the key and archive the row in '
                            'separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                END IF;
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                   AND EXISTS (
                       SELECT 1
                       FROM guitars_self_before AS guitars_before
                       JOIN guitars_self_after AS guitars_after
                           ON guitars_after."id" = guitars_before."id"
                       WHERE guitars_before._deleted_at IS NULL
                         AND guitars_after._deleted_at IS NOT NULL
                   ) THEN
                    UPDATE "testapp_setlist" AS guitars_child
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before."id" AS guitars_key
                        FROM guitars_self_before AS guitars_before
                        JOIN guitars_self_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_child."parent_id" = guitars_archived.guitars_key
                      AND guitars_child._deleted_at IS NULL;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_self_cascade_15_testapp_setlist_9_parent_id"
                AFTER UPDATE ON "testapp_setlist"
                REFERENCING OLD TABLE AS guitars_self_before NEW TABLE AS guitars_self_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_self_cascade_15_testapp_setlist_9_parent_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_self_cascade_15_testapp_setlist_9_parent_id" ON "testapp_setlist";

            DROP FUNCTION "soft_delete_self_cascade_15_testapp_setlist_9_parent_id"();
        """,
        ),

        # Soft Delete Self Cascade Trigger on "testapp_rack" via "parent_id"! [SQL:5ca18451ea00]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER "soft_delete_self_cascade_12_testapp_rack_9_parent_id" ON "testapp_rack";

            CREATE OR REPLACE FUNCTION "soft_delete_self_cascade_12_testapp_rack_9_parent_id"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_self_after AS guitars_after
                        WHERE guitars_after._deleted_at IS NOT NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_self_before AS guitars_before
                              WHERE guitars_before."id" = guitars_after."id"
                          )
                          AND EXISTS (
                              SELECT 1 FROM "testapp_rack" AS guitars_child
                              WHERE guitars_child._deleted_at IS NULL
                                AND (
                                    guitars_child."parent_id" = guitars_after."id"
                                    OR guitars_child."parent_id" IN (
                                        SELECT guitars_vanished."id"
                                        FROM guitars_self_before AS guitars_vanished
                                        WHERE guitars_vanished._deleted_at IS NULL
                                          AND NOT EXISTS (
                                              SELECT 1 FROM guitars_self_after AS guitars_kept
                                              WHERE guitars_kept."id"
                                                  = guitars_vanished."id"
                                          )
                                    )
                                )
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % archived a row whose primary key it also '
                            'rewrote, and a live child is left holding one of the two keys. The self '
                            'cascade trigger correlates its transition tables on the primary key, so '
                            'it cannot tell which before-row that archived row was, and would leak the '
                            'whole subtree permanently. Rewrite the key and archive the row in '
                            'separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                END IF;
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                   AND EXISTS (
                       SELECT 1
                       FROM guitars_self_before AS guitars_before
                       JOIN guitars_self_after AS guitars_after
                           ON guitars_after."id" = guitars_before."id"
                       WHERE guitars_before._deleted_at IS NULL
                         AND guitars_after._deleted_at IS NOT NULL
                   ) THEN
                    UPDATE "testapp_rack" AS guitars_child
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before."id" AS guitars_key
                        FROM guitars_self_before AS guitars_before
                        JOIN guitars_self_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_child."parent_id" = guitars_archived.guitars_key
                      AND guitars_child._deleted_at IS NULL;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_self_cascade_12_testapp_rack_9_parent_id"
                AFTER UPDATE ON "testapp_rack"
                REFERENCING OLD TABLE AS guitars_self_before NEW TABLE AS guitars_self_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_self_cascade_12_testapp_rack_9_parent_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_self_cascade_12_testapp_rack_9_parent_id" ON "testapp_rack";

            DROP FUNCTION "soft_delete_self_cascade_12_testapp_rack_9_parent_id"();
        """,
        ),

        # Soft Delete Self Cascade Trigger on "testapp_troupe" via "parent_id"! [SQL:a7fca3da7b27]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER "soft_delete_self_cascade_14_testapp_troupe_9_parent_id" ON "testapp_troupe";

            CREATE OR REPLACE FUNCTION "soft_delete_self_cascade_14_testapp_troupe_9_parent_id"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_self_after AS guitars_after
                        WHERE guitars_after._deleted_at IS NOT NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_self_before AS guitars_before
                              WHERE guitars_before."id" = guitars_after."id"
                          )
                          AND EXISTS (
                              SELECT 1 FROM "testapp_troupe" AS guitars_child
                              WHERE guitars_child._deleted_at IS NULL
                                AND (
                                    guitars_child."parent_id" = guitars_after."id"
                                    OR guitars_child."parent_id" IN (
                                        SELECT guitars_vanished."id"
                                        FROM guitars_self_before AS guitars_vanished
                                        WHERE guitars_vanished._deleted_at IS NULL
                                          AND NOT EXISTS (
                                              SELECT 1 FROM guitars_self_after AS guitars_kept
                                              WHERE guitars_kept."id"
                                                  = guitars_vanished."id"
                                          )
                                    )
                                )
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % archived a row whose primary key it also '
                            'rewrote, and a live child is left holding one of the two keys. The self '
                            'cascade trigger correlates its transition tables on the primary key, so '
                            'it cannot tell which before-row that archived row was, and would leak the '
                            'whole subtree permanently. Rewrite the key and archive the row in '
                            'separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                END IF;
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                   AND EXISTS (
                       SELECT 1
                       FROM guitars_self_before AS guitars_before
                       JOIN guitars_self_after AS guitars_after
                           ON guitars_after."id" = guitars_before."id"
                       WHERE guitars_before._deleted_at IS NULL
                         AND guitars_after._deleted_at IS NOT NULL
                   ) THEN
                    UPDATE "testapp_troupe" AS guitars_child
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before."id" AS guitars_key
                        FROM guitars_self_before AS guitars_before
                        JOIN guitars_self_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_child."parent_id" = guitars_archived.guitars_key
                      AND guitars_child._deleted_at IS NULL;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_self_cascade_14_testapp_troupe_9_parent_id"
                AFTER UPDATE ON "testapp_troupe"
                REFERENCING OLD TABLE AS guitars_self_before NEW TABLE AS guitars_self_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_self_cascade_14_testapp_troupe_9_parent_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_self_cascade_14_testapp_troupe_9_parent_id" ON "testapp_troupe";

            DROP FUNCTION "soft_delete_self_cascade_14_testapp_troupe_9_parent_id"();
        """,
        ),

    ]
