# Generated by makeguitarmigrations command! [DIGEST:335adff1fc364a641ff4db8fe460ab25]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0047_encore'),
    ]

    operations = [
        # Updated at Trigger on "testapp_encore" table! [SQL:0c9b9a14b6f5]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_encore" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_encore";
        """,
        ),

        # Soft Delete Rule on "testapp_encore" table! [SQL:efa4d06081c9]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_encore"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_encore"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_encore";
        """,
        ),

        # Soft Delete Related Rule on "testapp_encore" that is related to "testapp_band"! [SQL:dc9882f1e24b]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_encore"
                AS ON UPDATE TO "testapp_band"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_encore"
                    SET _deleted_at = NOW()
                    WHERE "band_id" = old."id"
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_encore" ON "testapp_band";
        """,
        ),

    ]
