# Generated by Django 5.2.15 on 2026-09-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0048_auto_enforcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encore',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encores', to='testapp.band'),
        ),
    ]
