# Generated by makeguitarmigrations command! [DIGEST:3525c5ae442e3bc7292516e94b61c6f9]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0051_rename_encore_to_callback'),
    ]

    operations = [
        # Updated at Trigger on "testapp_callback" table! [SQL:a8f374cd0ef8]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_callback";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_callback" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_callback";
        """,
        ),

        # Soft Delete Rule on "testapp_callback" table! [SQL:0df9983f85a7]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_callback"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_callback"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_callback";
        """,
        ),

    ]
