# Generated by makeguitarmigrations command! [DIGEST:e320e9416a02ae76d1de93cb8474dffd]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0053_callback_db_table'),
    ]

    operations = [
        # Updated at Trigger on "testapp_callbacks" table! [SQL:17e789963610]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_callbacks";

            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_callbacks" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_callbacks";
        """,
        ),

        # Soft Delete Rule on "testapp_callbacks" table! [SQL:9a4863e58da8]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_callbacks"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_callbacks"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_callbacks";
        """,
        ),

    ]
