# Generated by Django 5.2.15 on 2026-09-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0055_rename_callback_to_refrain'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refrain',
            new_name='refrain_deleted_at',
            old_name='encore_deleted_at',
        ),
        migrations.AlterField(
            model_name='refrain',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrains', to='testapp.band'),
        ),
    ]
