# Generated by makeguitarmigrations command! [DIGEST:a4f73e3582c6ea01a20eb4339649f22b]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0056_rename_encore_deleted_at_refrain_deleted_at_and_more'),
    ]

    operations = [
        # Soft Delete Related Rule on "testapp_album" that is related to "testapp_band"! [SQL:0538b64979bc]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_album"
                AS ON UPDATE TO "testapp_band"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_album"
                    SET _deleted_at = new._deleted_at
                    WHERE "band_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_album" ON "testapp_band";
        """,
        ),

        # Soft Delete Related Rule on "testapp_merch" that is related to "testapp_album"! [SQL:5a795ea3d52f]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_merch"
                AS ON UPDATE TO "testapp_album"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_merch"
                    SET _deleted_at = new._deleted_at
                    WHERE "album_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_merch" ON "testapp_album";
        """,
        ),

        # Soft Delete Related Rule on "testapp_merch" that is related to "testapp_album" via "bonus_album_id"! [SQL:fb2aee0ad137]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_merch_bonus_album_id"
                AS ON UPDATE TO "testapp_album"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_merch"
                    SET _deleted_at = new._deleted_at
                    WHERE "bonus_album_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_merch_bonus_album_id" ON "testapp_album";
        """,
        ),

        # Soft Delete Related Rule on "testapp_section" that is related to "testapp_ensemble"! [SQL:4ec973294834]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_section"
                AS ON UPDATE TO "testapp_ensemble"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_section"
                    SET _deleted_at = new._deleted_at
                    WHERE "orchestra_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_section" ON "testapp_ensemble";
        """,
        ),

        # Soft Delete Related Rule on "testapp_booking" that is related to "testapp_label"! [SQL:1cca3380fa54]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_booking"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_booking"
                    SET _deleted_at = new._deleted_at
                    WHERE "label_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_booking" ON "testapp_label";
        """,
        ),

        # Soft Delete Related Rule on "testapp_court" that is related to "testapp_label"! [SQL:30cd50fc681f]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_court"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_court"
                    SET _deleted_at = new._deleted_at
                    WHERE "label_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_court" ON "testapp_label";
        """,
        ),

        # Soft Delete Related Rule on "testapp_festival" that is related to "testapp_label"! [SQL:322708a563d1]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_festival"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_festival"
                    SET _deleted_at = new._deleted_at
                    WHERE "market_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_festival" ON "testapp_label";
        """,
        ),

        # Soft Delete Related Rule on "testapp_hall" that is related to "testapp_label"! [SQL:aedaa658c129]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_hall"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_hall"
                    SET _deleted_at = new._deleted_at
                    WHERE "label_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_hall" ON "testapp_label";
        """,
        ),

        # Soft Delete Related Rule on "testapp_release" that is related to "testapp_label"! [SQL:b0c289d73cd4]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_release"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_release"
                    SET _deleted_at = new._deleted_at
                    WHERE "label_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_release" ON "testapp_label";
        """,
        ),

        # Soft Delete Related Rule on "testapp_tour" that is related to "testapp_label"! [SQL:96d41188e554]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_tour"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_tour"
                    SET _deleted_at = new._deleted_at
                    WHERE "label_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_tour" ON "testapp_label";
        """,
        ),

        # Soft Delete Related Rule on "testapp_track" that is related to "testapp_label"! [SQL:07045916046c]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_track"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_track"
                    SET _deleted_at = new._deleted_at
                    WHERE "label_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_track" ON "testapp_label";
        """,
        ),

        # Soft Delete Related Rule on "testapp_troupe" that is related to "testapp_label"! [SQL:90eed053eb23]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_troupe"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_troupe"
                    SET _deleted_at = new._deleted_at
                    WHERE "label_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_troupe" ON "testapp_label";
        """,
        ),

        # Soft Delete Related Rule on "testapp_venue" that is related to "testapp_label"! [SQL:e585e658a0f7]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_venue"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_venue"
                    SET _deleted_at = new._deleted_at
                    WHERE "label_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_venue" ON "testapp_label";
        """,
        ),

        # Soft Delete Related Rule on "testapp_review" that is related to "testapp_release"! [SQL:dfa3d3293ba7]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_review"
                AS ON UPDATE TO "testapp_release"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_review"
                    SET _deleted_at = new._deleted_at
                    WHERE "release_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_review" ON "testapp_release";
        """,
        ),

        # Soft Delete Related Rule on "testapp_track" that is related to "testapp_release"! [SQL:5278fbc74dbe]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_track"
                AS ON UPDATE TO "testapp_release"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_track"
                    SET _deleted_at = new._deleted_at
                    WHERE "release_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_track" ON "testapp_release";
        """,
        ),

        # Soft Delete Related Rule on "testapp_setlistentry" that is related to "testapp_setlist"! [SQL:5f78110d88a4]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_setlistentry"
                AS ON UPDATE TO "testapp_setlist"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_setlistentry"
                    SET _deleted_at = new._deleted_at
                    WHERE "setlist_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_setlistentry" ON "testapp_setlist";
        """,
        ),

    ]
