# Generated by makeguitarmigrations command! [DIGEST:d0a2a1ad52f340c2d86226a342a415d9]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0057_auto_enforcement'),
    ]

    operations = [
        # Soft Delete Revive Rule on "testapp_album" that is related to "testapp_band"! [SQL:3e048bf250c9]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_13_testapp_album"
                AS ON UPDATE TO "testapp_band"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_album"
                    SET _deleted_at = NULL
                    WHERE "band_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_13_testapp_album" ON "testapp_band";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_merch" that is related to "testapp_album"! [SQL:4974d36a0267]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_13_testapp_merch"
                AS ON UPDATE TO "testapp_album"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_merch"
                    SET _deleted_at = NULL
                    WHERE "album_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_13_testapp_merch" ON "testapp_album";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_merch" that is related to "testapp_album" via "bonus_album_id"! [SQL:af89f111e7be]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_13_testapp_merch_14_bonus_album_id"
                AS ON UPDATE TO "testapp_album"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_merch"
                    SET _deleted_at = NULL
                    WHERE "bonus_album_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_13_testapp_merch_14_bonus_album_id" ON "testapp_album";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_section" that is related to "testapp_ensemble"! [SQL:96565a9d73a3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_15_testapp_section"
                AS ON UPDATE TO "testapp_ensemble"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_section"
                    SET _deleted_at = NULL
                    WHERE "orchestra_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_15_testapp_section" ON "testapp_ensemble";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_booking" that is related to "testapp_label"! [SQL:199b51b9f877]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_15_testapp_booking"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_booking"
                    SET _deleted_at = NULL
                    WHERE "label_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_15_testapp_booking" ON "testapp_label";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_court" that is related to "testapp_label"! [SQL:f78d8ad97460]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_13_testapp_court"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_court"
                    SET _deleted_at = NULL
                    WHERE "label_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_13_testapp_court" ON "testapp_label";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_festival" that is related to "testapp_label"! [SQL:108d1f466ad1]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_16_testapp_festival"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_festival"
                    SET _deleted_at = NULL
                    WHERE "market_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_16_testapp_festival" ON "testapp_label";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_hall" that is related to "testapp_label"! [SQL:13065599a054]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_12_testapp_hall"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_hall"
                    SET _deleted_at = NULL
                    WHERE "label_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_12_testapp_hall" ON "testapp_label";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_release" that is related to "testapp_label"! [SQL:c993291accbc]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_15_testapp_release"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_release"
                    SET _deleted_at = NULL
                    WHERE "label_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_15_testapp_release" ON "testapp_label";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_tour" that is related to "testapp_label"! [SQL:a72b76761d21]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_12_testapp_tour"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_tour"
                    SET _deleted_at = NULL
                    WHERE "label_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_12_testapp_tour" ON "testapp_label";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_track" that is related to "testapp_label"! [SQL:414c0ac13ee5]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_13_testapp_track"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_track"
                    SET _deleted_at = NULL
                    WHERE "label_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_13_testapp_track" ON "testapp_label";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_troupe" that is related to "testapp_label"! [SQL:3206458819a4]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_14_testapp_troupe"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_troupe"
                    SET _deleted_at = NULL
                    WHERE "label_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_14_testapp_troupe" ON "testapp_label";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_venue" that is related to "testapp_label"! [SQL:b7a81d438531]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_13_testapp_venue"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_venue"
                    SET _deleted_at = NULL
                    WHERE "label_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_13_testapp_venue" ON "testapp_label";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_review" that is related to "testapp_release"! [SQL:e0b37d8b9e92]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_14_testapp_review"
                AS ON UPDATE TO "testapp_release"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_review"
                    SET _deleted_at = NULL
                    WHERE "release_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_14_testapp_review" ON "testapp_release";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_track" that is related to "testapp_release"! [SQL:a6fadb178dd9]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_13_testapp_track"
                AS ON UPDATE TO "testapp_release"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_track"
                    SET _deleted_at = NULL
                    WHERE "release_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_13_testapp_track" ON "testapp_release";
        """,
        ),

        # Soft Delete Revive Rule on "testapp_setlistentry" that is related to "testapp_setlist"! [SQL:ecac033a8a78]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_revive_20_testapp_setlistentry"
                AS ON UPDATE TO "testapp_setlist"
                WHERE old._deleted_at IS NOT NULL AND new._deleted_at IS NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_setlistentry"
                    SET _deleted_at = NULL
                    WHERE "setlist_id" = old."id"
                      AND _deleted_at = old._deleted_at
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_revive_20_testapp_setlistentry" ON "testapp_setlist";
        """,
        ),

    ]
