# Generated by makeguitarmigrations command! [DIGEST:0a0b0562db937242da72d52e2ea1cf4c]

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0059_retirement_host'),
    ]

    operations = [
        # Soft Delete Related Rule on "testapp_headlinefestival" that is related to "testapp_label"! [SQL:3ebf851f36a1]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_headlinefestival"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_festival"
                    SET _deleted_at = new._deleted_at
                    WHERE "id" IN (
                        SELECT "touringfestival_ptr_id" FROM "testapp_headlinefestival" WHERE "sponsor_id" = old."id"
                    )
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_headlinefestival" ON "testapp_label";
        """,
        ),
        # Soft Delete Revive Trigger on "testapp_headlinefestival" that is related to "testapp_label"! [SQL:93667fdcf44a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_revive_13_testapp_label_24_testapp_headlinefestival"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_festival" AS guitars_child
                    SET _deleted_at = NULL, _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NOT NULL
                          AND guitars_after._deleted_at IS NULL
                    ) AS guitars_revived
                    WHERE guitars_child."id" IN (
                            SELECT guitars_link."touringfestival_ptr_id" FROM "testapp_headlinefestival" AS guitars_link
                            WHERE guitars_link."sponsor_id" = guitars_revived."id"
                        )
                      AND guitars_child._deleted_at = guitars_revived._deleted_at;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_revive_13_testapp_label_24_testapp_headlinefestival"
                AFTER UPDATE ON "testapp_label"
                REFERENCING OLD TABLE AS guitars_revive_before NEW TABLE AS guitars_revive_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_revive_13_testapp_label_24_testapp_headlinefestival"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_revive_13_testapp_label_24_testapp_headlinefestival" ON "testapp_label";

            DROP FUNCTION "soft_delete_revive_13_testapp_label_24_testapp_headlinefestival"();
        """,
        ),
        # Soft Delete Related Rule on "testapp_touringfestival" that is related to "testapp_label"! [SQL:d2cd5e100ba2]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_touringfestival"
                AS ON UPDATE TO "testapp_label"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_festival"
                    SET _deleted_at = new._deleted_at
                    WHERE "id" IN (
                        SELECT "festival_ptr_id" FROM "testapp_touringfestival" WHERE "promoter_id" = old."id"
                    )
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_touringfestival" ON "testapp_label";
        """,
        ),
        # Soft Delete Revive Trigger on "testapp_touringfestival" that is related to "testapp_label"! [SQL:51af0f663483]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_revive_13_testapp_label_23_testapp_touringfestival"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_festival" AS guitars_child
                    SET _deleted_at = NULL, _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NOT NULL
                          AND guitars_after._deleted_at IS NULL
                    ) AS guitars_revived
                    WHERE guitars_child."id" IN (
                            SELECT guitars_link."festival_ptr_id" FROM "testapp_touringfestival" AS guitars_link
                            WHERE guitars_link."promoter_id" = guitars_revived."id"
                        )
                      AND guitars_child._deleted_at = guitars_revived._deleted_at;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_revive_13_testapp_label_23_testapp_touringfestival"
                AFTER UPDATE ON "testapp_label"
                REFERENCING OLD TABLE AS guitars_revive_before NEW TABLE AS guitars_revive_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_revive_13_testapp_label_23_testapp_touringfestival"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_revive_13_testapp_label_23_testapp_touringfestival" ON "testapp_label";

            DROP FUNCTION "soft_delete_revive_13_testapp_label_23_testapp_touringfestival"();
        """,
        ),
    ]
