# Generated by Django 5.2.15 on 2026-10-02 18:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0061_retirement_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='testapp.clause')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='QuantityCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.condition')),
                ('minimum', models.IntegerField(default=1)),
            ],
            bases=('testapp.condition',),
        ),
        migrations.CreateModel(
            name='DiscountReward',
            fields=[
                ('reward_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.reward')),
                ('percent', models.IntegerField(default=0)),
            ],
            bases=('testapp.reward',),
        ),
        migrations.CreateModel(
            name='GiftReward',
            fields=[
                ('reward_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.reward')),
                ('sku', models.CharField(default='', max_length=40)),
            ],
            bases=('testapp.reward',),
        ),
        migrations.CreateModel(
            name='ShippingReward',
            fields=[
                ('reward_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.reward')),
                ('free_over', models.IntegerField(default=0)),
            ],
            bases=('testapp.reward',),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [models.Index(condition=models.Q(('_deleted_at__isnull', True)), fields=['_deleted_at'], name='offer_deleted_at')],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='testapp.offer')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='reward',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='testapp.tier'),
        ),
        migrations.AddField(
            model_name='clause',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='testapp.tier'),
        ),
        migrations.CreateModel(
            name='ConditionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('_created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated at')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='testapp.quantitycondition')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='condition',
            index=models.Index(condition=models.Q(('_deleted_at__isnull', True)), fields=['_deleted_at'], name='condition_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='tier',
            index=models.Index(condition=models.Q(('_deleted_at__isnull', True)), fields=['_deleted_at'], name='tier_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(condition=models.Q(('_deleted_at__isnull', True)), fields=['_deleted_at'], name='reward_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(condition=models.Q(('_deleted_at__isnull', True)), fields=['_deleted_at'], name='clause_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='conditionnote',
            index=models.Index(condition=models.Q(('_deleted_at__isnull', True)), fields=['_deleted_at'], name='conditionnote_deleted_at'),
        ),
    ]
