# Generated by makeguitarmigrations command! [DIGEST:bab471ac174bf97da83d01507d5a9f72]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0065_ledger_cue_stagecraft_ledger_ledger_deleted_at_and_more'),
    ]

    operations = [
        # Updated at Trigger on "testapp_ledger" table! [SQL:2d4b6dadf9d1]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_ledger" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_ledger";
        """,
        ),

        # Soft Delete Rule on "testapp_ledger" table! [SQL:aaa74da032c6]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_ledger"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_ledger"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_ledger";
        """,
        ),

        # Updated at Trigger on "testapp_stagecraft" table! [SQL:ff4be2aa7331]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_stagecraft" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_stagecraft";
        """,
        ),

        # Soft Delete Rule on "testapp_stagecraft" table! [SQL:3d3526389577]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_stagecraft"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_stagecraft"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_stagecraft";
        """,
        ),

        # Updated at Trigger on "testapp_cue" table! [SQL:50c2a753c7f3]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_cue" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_cue";
        """,
        ),

        # Soft Delete Rule on "testapp_cue" table! [SQL:e54f1ba8e854]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_cue"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_cue"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_cue";
        """,
        ),

        # Soft Delete Related Rule on "testapp_cue" that is related to "testapp_ledger"! [SQL:4dbe47701ebb]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_related_testapp_cue"
                AS ON UPDATE TO "testapp_ledger"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_cue"
                    SET _deleted_at = new._deleted_at
                    WHERE "ledger_id" = old."id"
                      AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_related_testapp_cue" ON "testapp_ledger";
        """,
        ),

        # Soft Delete Revive Trigger on "testapp_cue" that is related to "testapp_ledger"! [SQL:9d9818195614]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_revive_14_testapp_ledger_11_testapp_cue"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    UPDATE "testapp_cue" AS guitars_child
                    SET _deleted_at = NULL, _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NOT NULL
                          AND guitars_after._deleted_at IS NULL
                    ) AS guitars_revived
                    WHERE guitars_child."ledger_id" = guitars_revived."id"
                      AND guitars_child._deleted_at = guitars_revived._deleted_at;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_revive_14_testapp_ledger_11_testapp_cue"
                AFTER UPDATE ON "testapp_ledger"
                REFERENCING OLD TABLE AS guitars_revive_before NEW TABLE AS guitars_revive_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_revive_14_testapp_ledger_11_testapp_cue"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_revive_14_testapp_ledger_11_testapp_cue" ON "testapp_ledger";

            DROP FUNCTION "soft_delete_revive_14_testapp_ledger_11_testapp_cue"();
        """,
        ),

        # Soft Delete Self Cascade Trigger on "testapp_ledger" via "mirror_id"! [SQL:aea6fc0d2c1d]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_self_cascade_14_testapp_ledger_9_mirror_id"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_self_after AS guitars_after
                        WHERE guitars_after._deleted_at IS NOT NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_self_before AS guitars_before
                              WHERE guitars_before."id" = guitars_after."id"
                          )
                          AND EXISTS (
                              SELECT 1 FROM "testapp_ledger" AS guitars_child
                              WHERE guitars_child._deleted_at IS NULL
                                AND (
                                    guitars_child."mirror_id" = guitars_after."id"
                                    OR guitars_child."mirror_id" IN (
                                        SELECT guitars_vanished."id"
                                        FROM guitars_self_before AS guitars_vanished
                                        WHERE guitars_vanished._deleted_at IS NULL
                                          AND NOT EXISTS (
                                              SELECT 1 FROM guitars_self_after AS guitars_kept
                                              WHERE guitars_kept."id"
                                                  = guitars_vanished."id"
                                          )
                                    )
                                )
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % archived a row whose primary key it also '
                            'rewrote, and a live child is left holding one of the two keys. The self '
                            'cascade trigger correlates its transition tables on the primary key, so '
                            'it cannot tell which before-row that archived row was, and would leak the '
                            'whole subtree permanently. Rewrite the key and archive the row in '
                            'separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                END IF;
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                   AND EXISTS (
                       SELECT 1
                       FROM guitars_self_before AS guitars_before
                       JOIN guitars_self_after AS guitars_after
                           ON guitars_after."id" = guitars_before."id"
                       WHERE guitars_before._deleted_at IS NULL
                         AND guitars_after._deleted_at IS NOT NULL
                   ) THEN
                    UPDATE "testapp_ledger" AS guitars_child
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before."id" AS guitars_key
                        FROM guitars_self_before AS guitars_before
                        JOIN guitars_self_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_child."mirror_id" = guitars_archived.guitars_key
                      AND guitars_child._deleted_at IS NULL;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_self_cascade_14_testapp_ledger_9_mirror_id"
                AFTER UPDATE ON "testapp_ledger"
                REFERENCING OLD TABLE AS guitars_self_before NEW TABLE AS guitars_self_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_self_cascade_14_testapp_ledger_9_mirror_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_self_cascade_14_testapp_ledger_9_mirror_id" ON "testapp_ledger";

            DROP FUNCTION "soft_delete_self_cascade_14_testapp_ledger_9_mirror_id"();
        """,
        ),

        # Soft Delete Self Cascade Trigger on "testapp_ledger" via "parent_id"! [SQL:f29d313535d3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_self_cascade_14_testapp_ledger_9_parent_id"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_self_after AS guitars_after
                        WHERE guitars_after._deleted_at IS NOT NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_self_before AS guitars_before
                              WHERE guitars_before."id" = guitars_after."id"
                          )
                          AND EXISTS (
                              SELECT 1 FROM "testapp_ledger" AS guitars_child
                              WHERE guitars_child._deleted_at IS NULL
                                AND (
                                    guitars_child."parent_id" = guitars_after."id"
                                    OR guitars_child."parent_id" IN (
                                        SELECT guitars_vanished."id"
                                        FROM guitars_self_before AS guitars_vanished
                                        WHERE guitars_vanished._deleted_at IS NULL
                                          AND NOT EXISTS (
                                              SELECT 1 FROM guitars_self_after AS guitars_kept
                                              WHERE guitars_kept."id"
                                                  = guitars_vanished."id"
                                          )
                                    )
                                )
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % archived a row whose primary key it also '
                            'rewrote, and a live child is left holding one of the two keys. The self '
                            'cascade trigger correlates its transition tables on the primary key, so '
                            'it cannot tell which before-row that archived row was, and would leak the '
                            'whole subtree permanently. Rewrite the key and archive the row in '
                            'separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                END IF;
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                   AND EXISTS (
                       SELECT 1
                       FROM guitars_self_before AS guitars_before
                       JOIN guitars_self_after AS guitars_after
                           ON guitars_after."id" = guitars_before."id"
                       WHERE guitars_before._deleted_at IS NULL
                         AND guitars_after._deleted_at IS NOT NULL
                   ) THEN
                    UPDATE "testapp_ledger" AS guitars_child
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before."id" AS guitars_key
                        FROM guitars_self_before AS guitars_before
                        JOIN guitars_self_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_child."parent_id" = guitars_archived.guitars_key
                      AND guitars_child._deleted_at IS NULL;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_self_cascade_14_testapp_ledger_9_parent_id"
                AFTER UPDATE ON "testapp_ledger"
                REFERENCING OLD TABLE AS guitars_self_before NEW TABLE AS guitars_self_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_self_cascade_14_testapp_ledger_9_parent_id"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_self_cascade_14_testapp_ledger_9_parent_id" ON "testapp_ledger";

            DROP FUNCTION "soft_delete_self_cascade_14_testapp_ledger_9_parent_id"();
        """,
        ),

        # Soft Delete Owned Rule on "testapp_ledger" that is owned by "testapp_stagecraft" via "ledger_id"! [SQL:43603ef2ae15]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_14_testapp_ledger_9_ledger_id"
                AS ON UPDATE TO "testapp_stagecraft"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_ledger"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."ledger_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_stagecraft" AS guitars_owner
                          WHERE guitars_owner."ledger_id" = old."ledger_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_14_testapp_ledger_9_ledger_id" ON "testapp_stagecraft";
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_ledger" that is owned by "testapp_stagecraft" via "ledger_id"! [SQL:013227c06b5c]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_18_testapp_stagecraft_14_tes_890d581810"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_owned_before AS guitars_before
                        JOIN "testapp_ledger" AS guitars_dependent
                            ON guitars_dependent."id" = guitars_before."ledger_id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_before."ledger_id" IS NOT NULL
                          AND guitars_dependent._deleted_at IS NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_owned_after AS guitars_after
                              WHERE guitars_after."id" = guitars_before."id"
                          )
                          AND NOT EXISTS (
                              SELECT 1 FROM "testapp_stagecraft" AS guitars_owner
                              WHERE guitars_owner."ledger_id" = guitars_before."ledger_id"
                                AND guitars_owner._deleted_at IS NULL
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % rewrote the primary key of a live owning row '
                            'whose dependent is now held by no live owner. The owned sweep correlates '
                            'its transition tables on the primary key, so it cannot tell whether that '
                            'row was archived, and would leak the dependent permanently. Rewrite the '
                            'key and archive the row in separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                    UPDATE "testapp_ledger" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_owned_before AS guitars_before
                        JOIN guitars_owned_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_before."ledger_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."ledger_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_stagecraft" AS guitars_owner
                          WHERE guitars_owner."ledger_id" = guitars_archived."ledger_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_18_testapp_stagecraft_14_tes_890d581810"
                AFTER UPDATE ON "testapp_stagecraft"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_18_testapp_stagecraft_14_tes_890d581810"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_18_testapp_stagecraft_14_tes_890d581810" ON "testapp_stagecraft";

            DROP FUNCTION "soft_delete_owned_sweep_18_testapp_stagecraft_14_tes_890d581810"();
        """,
        ),

    ]
