# Generated by makeguitarmigrations command! [DIGEST:28faf3a52e8d44fe222da9eafbd45ef1]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_enforcement_trigger_function'),
        ('testapp', '0079_clipping_plinth_smudge'),
    ]

    operations = [
        # Updated at Trigger on "testapp_smudge" table! [SQL:c218db4802e4]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_smudge" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_smudge";
        """,
        ),

        # Soft Delete Rule on "testapp_smudge" table! [SQL:375766d38300]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_smudge"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_smudge"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_smudge";
        """,
        ),

        # Updated at Trigger on "testapp_plinth" table! [SQL:f36b5b31932a]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_plinth" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_plinth";
        """,
        ),

        # Soft Delete Rule on "testapp_plinth" table! [SQL:91d51f540530]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_plinth"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_plinth"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_plinth";
        """,
        ),

        # Updated at Trigger on "testapp_clipping" table! [SQL:985bf600dfc0]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_clipping" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "testapp_clipping";
        """,
        ),

        # Soft Delete Rule on "testapp_clipping" table! [SQL:65f7b5f62f6b]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_clipping"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_clipping"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_clipping";
        """,
        ),

        # Soft Delete Owned Rule on "testapp_signboard" that is owned by "testapp_plinth" via "signboard_id"! [SQL:adf308129bb6]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE "soft_delete_owned_17_testapp_signboard_12_signboard_id"
                AS ON UPDATE TO "testapp_plinth"
                WHERE old._deleted_at IS NULL AND new._deleted_at IS NOT NULL AND
                      COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO ALSO (
                    UPDATE "testapp_signboard"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."signboard_id"
                      AND _deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_plinth" AS guitars_owner
                          WHERE guitars_owner."signboard_id" = old."signboard_id"
                            AND guitars_owner."id" <> old."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                );
        """,
            reverse_sql="""
            DROP RULE "soft_delete_owned_17_testapp_signboard_12_signboard_id" ON "testapp_plinth";
        """,
        ),

        # Soft Delete Owned Sweep on "testapp_signboard" that is owned by "testapp_plinth" via "signboard_id"! [SQL:82e2bf149464]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_14_testapp_plinth_17_testapp_4d155cfaa0"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_owned_before AS guitars_before
                        JOIN "testapp_signboard" AS guitars_dependent
                            ON guitars_dependent."id" = guitars_before."signboard_id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_before."signboard_id" IS NOT NULL
                          AND guitars_dependent._deleted_at IS NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_owned_after AS guitars_after
                              WHERE guitars_after."id" = guitars_before."id"
                          )
                          AND NOT EXISTS (
                              SELECT 1 FROM "testapp_plinth" AS guitars_owner
                              WHERE guitars_owner."signboard_id" = guitars_before."signboard_id"
                                AND guitars_owner._deleted_at IS NULL
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % rewrote the primary key of a live owning row '
                            'whose dependent is now held by no live owner. The owned sweep correlates '
                            'its transition tables on the primary key, so it cannot tell whether that '
                            'row was archived, and would leak the dependent permanently. Rewrite the '
                            'key and archive the row in separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                    UPDATE "testapp_signboard" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_owned_before AS guitars_before
                        JOIN guitars_owned_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_before."signboard_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."signboard_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "testapp_plinth" AS guitars_owner
                          WHERE guitars_owner."signboard_id" = guitars_archived."signboard_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_14_testapp_plinth_17_testapp_4d155cfaa0"
                AFTER UPDATE ON "testapp_plinth"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_14_testapp_plinth_17_testapp_4d155cfaa0"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_14_testapp_plinth_17_testapp_4d155cfaa0" ON "testapp_plinth";

            DROP FUNCTION "soft_delete_owned_sweep_14_testapp_plinth_17_testapp_4d155cfaa0"();
        """,
        ),

    ]
