# Generated by makeguitarmigrations command! [DIGEST:fb3b8ab6bc4dcc3244fbe256bac58c9c]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0081_retirement_host_after_plinth'),
    ]

    operations = [
        # Define function for updated at row triggers! [SQL:1842e8945a8d]
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION stamp_updated_at()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                NEW._updated_at := NOW();
                RETURN NEW;
            END;
            $$
        """,
            reverse_sql="""
            DROP FUNCTION stamp_updated_at();
        """,
        ),

    ]
