# Generated by makeguitarmigrations command! [DIGEST:032c280367e06b93ed1f87e9e4424390]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0082_auto_enforcement_stamp_function'),
    ]

    operations = [
        # Updated at Trigger on "testapp_genre" table! [SQL:7c4f20e3950f]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_genre"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_genre" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_band" table! [SQL:e7dc339ed451]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_band"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_band" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_presskit" table! [SQL:2dd777f8c1de]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_presskit"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_presskit" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_album" table! [SQL:a009035f3ad7]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_album"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_album" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_ensemble" table! [SQL:535a13a0831f]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_ensemble"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_ensemble" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_merch" table! [SQL:12296b39cf57]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_merch"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_merch" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_patron" table! [SQL:044534e4ae7a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_patron"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_patron" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_stagehand" table! [SQL:fed77f79c361]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_stagehand"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_stagehand" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_rider" table! [SQL:39451137ac4a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_rider"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_rider" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_residency" table! [SQL:ec08778512c3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_residency"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_residency" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_section" table! [SQL:dfb7d6292eb6]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_section"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_section" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_label" table! [SQL:503afbf61506]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_label"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_label" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_release" table! [SQL:ec75528da37f]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_release"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_release" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_track" table! [SQL:29baf7f7e58b]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_track"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_track" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_tour" table! [SQL:1adfcaf4e2b8]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_tour"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_tour" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_booking" table! [SQL:edd55997e920]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_booking"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_booking" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_review" table! [SQL:f3b18136a30b]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_review"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_review" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_festival" table! [SQL:9b49d2197f8f]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_festival"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_festival" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_venue" table! [SQL:8d372f19d1db]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_venue"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_venue" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_hall" table! [SQL:43ac08361092]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_hall"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_hall" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_court" table! [SQL:150e3db348f2]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_court"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_court" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_placard" table! [SQL:e21820be5852]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_placard"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_placard" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_kiosk" table! [SQL:d6ae4e7a3036]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_kiosk"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_kiosk" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_foyer" table! [SQL:1c7fae9cdcef]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_foyer"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_foyer" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_awning" table! [SQL:449c8ead7dd3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_awning"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_awning" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_banner" table! [SQL:3d98d8c6ef9a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_banner"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_banner" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_billboard" table! [SQL:dff5d1551484]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_billboard"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_billboard" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_signboard" table! [SQL:90e67d31730a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_signboard"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_signboard" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_scribble" table! [SQL:9f2e0fbf4413]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_scribble"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_scribble" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_setlist" table! [SQL:72192f38f3cf]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_setlist"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_setlist" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_setlistentry" table! [SQL:ade834030427]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_setlistentry"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_setlistentry" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_riser" table! [SQL:3005ab9cbd76]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_riser"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_riser" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_rack" table! [SQL:99e34dfcdec3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_rack"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_rack" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_troupe" table! [SQL:75cbeeccf9ff]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_troupe"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_troupe" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_callbacks" table! [SQL:d064b165fdf6]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_callbacks"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_callbacks" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_offer" table! [SQL:63e6085e4b8e]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_offer"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_offer" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_tier" table! [SQL:09a618b77606]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_tier"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_tier" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_clause" table! [SQL:bfa3ab2bf085]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_clause"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_clause" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_condition" table! [SQL:9e182d889856]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_condition"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_condition" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_reward" table! [SQL:44f1bf887476]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_reward"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_reward" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_conditionnote" table! [SQL:266d8af45b70]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_conditionnote"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_conditionnote" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_ledger" table! [SQL:20b3d5ce13ad]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_ledger"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_ledger" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_stagecraft" table! [SQL:4e5b19d55255]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_stagecraft"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_stagecraft" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_cue" table! [SQL:a66594b15349]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_cue"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_cue" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_cuenote" table! [SQL:7f98fca2f57a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_cuenote"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_cuenote" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_rig" table! [SQL:4f006502c6e4]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_rig"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_rig" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_roadie" table! [SQL:3a91d174d9ec]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_roadie"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_roadie" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_catalog" table! [SQL:1ec8ebb67dec]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_catalog"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_catalog" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_listing" table! [SQL:71b6ba598423]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_listing"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_listing" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_ticket" table! [SQL:40426eb29b4d]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_ticket"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_ticket" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_seat" table! [SQL:250ab25c564c]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_seat"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_seat" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_folio" table! [SQL:ff05cd1e2550]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_folio"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_folio" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_smudge" table! [SQL:f7ececcb8397]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_smudge"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_smudge" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_plinth" table! [SQL:d2d9878999e5]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_plinth"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_plinth" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

        # Updated at Trigger on "testapp_clipping" table! [SQL:dae021248c53]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "testapp_clipping"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                AFTER UPDATE ON "testapp_clipping" REFERENCING NEW TABLE AS new_table
                FOR EACH STATEMENT
                WHEN (pg_trigger_depth() = 0)
                EXECUTE FUNCTION set_updated_at('id');
        """,
        ),

    ]
