# Generated by makeguitarmigrations command! [DIGEST:70e7cd87c92b85ca784f3532733014c9]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0094_retirement_host_after_self_arms'),
    ]

    operations = [
        # Soft Delete Cascade Guard on "testapp_album" table! [SQL:07f7404c99b3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_13_testapp_album"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_album"._deleted_at%TYPE;
            BEGIN
                IF NEW."band_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."band_id" IS DISTINCT FROM OLD."band_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_band" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."band_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_13_testapp_album"
                BEFORE INSERT OR UPDATE ON "testapp_album"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_13_testapp_album"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_13_testapp_album" ON "testapp_album";

            DROP FUNCTION "soft_delete_guard_on_13_testapp_album"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_baton" table! [SQL:87586cb3d56d]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_13_testapp_baton"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_baton"._deleted_at%TYPE;
            BEGIN
                IF NEW."relay_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."relay_id" IS DISTINCT FROM OLD."relay_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_relay" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."relay_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_13_testapp_baton"
                BEFORE INSERT OR UPDATE ON "testapp_baton"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_13_testapp_baton"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_13_testapp_baton" ON "testapp_baton";

            DROP FUNCTION "soft_delete_guard_on_13_testapp_baton"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_booking" table! [SQL:72d24b84cdbc]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_15_testapp_booking"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_booking"._deleted_at%TYPE;
            BEGIN
                IF NEW."label_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."label_id" IS DISTINCT FROM OLD."label_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."label_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_15_testapp_booking"
                BEFORE INSERT OR UPDATE ON "testapp_booking"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_15_testapp_booking"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_15_testapp_booking" ON "testapp_booking";

            DROP FUNCTION "soft_delete_guard_on_15_testapp_booking"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_clause" table! [SQL:13ebad8c0b17]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_14_testapp_clause"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_clause"._deleted_at%TYPE;
            BEGIN
                IF NEW."tier_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."tier_id" IS DISTINCT FROM OLD."tier_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_tier" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."tier_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_14_testapp_clause"
                BEFORE INSERT OR UPDATE ON "testapp_clause"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_14_testapp_clause"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_14_testapp_clause" ON "testapp_clause";

            DROP FUNCTION "soft_delete_guard_on_14_testapp_clause"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_condition" table! [SQL:af82c3a0a5e5]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_17_testapp_condition"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_condition"._deleted_at%TYPE;
            BEGIN
                IF NEW."clause_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."clause_id" IS DISTINCT FROM OLD."clause_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_clause" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."clause_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_17_testapp_condition"
                BEFORE INSERT OR UPDATE ON "testapp_condition"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_17_testapp_condition"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_17_testapp_condition" ON "testapp_condition";

            DROP FUNCTION "soft_delete_guard_on_17_testapp_condition"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_conditionnote" table! [SQL:8f4ef7abbb95]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_21_testapp_conditionnote"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_conditionnote"._deleted_at%TYPE;
            BEGIN
                IF NEW."condition_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."condition_id" IS DISTINCT FROM OLD."condition_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_condition" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."condition_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_21_testapp_conditionnote"
                BEFORE INSERT OR UPDATE ON "testapp_conditionnote"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_21_testapp_conditionnote"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_21_testapp_conditionnote" ON "testapp_conditionnote";

            DROP FUNCTION "soft_delete_guard_on_21_testapp_conditionnote"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_court" table! [SQL:cb8c69c64b27]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_13_testapp_court"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_court"._deleted_at%TYPE;
            BEGIN
                IF NEW."label_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."label_id" IS DISTINCT FROM OLD."label_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."label_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_13_testapp_court"
                BEFORE INSERT OR UPDATE ON "testapp_court"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_13_testapp_court"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_13_testapp_court" ON "testapp_court";

            DROP FUNCTION "soft_delete_guard_on_13_testapp_court"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_cue" table! [SQL:832061eadc2a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_11_testapp_cue"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_cue"._deleted_at%TYPE;
            BEGIN
                IF NEW."ledger_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."ledger_id" IS DISTINCT FROM OLD."ledger_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_ledger" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."ledger_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_11_testapp_cue"
                BEFORE INSERT OR UPDATE ON "testapp_cue"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_11_testapp_cue"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_11_testapp_cue" ON "testapp_cue";

            DROP FUNCTION "soft_delete_guard_on_11_testapp_cue"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_festival" table! [SQL:586041d57e11]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_16_testapp_festival"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_festival"._deleted_at%TYPE;
            BEGIN
                IF NEW."market_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."market_id" IS DISTINCT FROM OLD."market_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."market_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_16_testapp_festival"
                BEFORE INSERT OR UPDATE ON "testapp_festival"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_16_testapp_festival"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_16_testapp_festival" ON "testapp_festival";

            DROP FUNCTION "soft_delete_guard_on_16_testapp_festival"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_folio" table! [SQL:08bd8758ccea]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_13_testapp_folio"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_folio"._deleted_at%TYPE;
            BEGIN
                IF NEW."parent_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."parent_id" IS DISTINCT FROM OLD."parent_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_folio" AS guitars_parent
                    WHERE guitars_parent."code" = NEW."parent_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_13_testapp_folio"
                BEFORE INSERT OR UPDATE ON "testapp_folio"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_13_testapp_folio"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_13_testapp_folio" ON "testapp_folio";

            DROP FUNCTION "soft_delete_guard_on_13_testapp_folio"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_hall" table! [SQL:8670b4363aa9]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_12_testapp_hall"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_hall"._deleted_at%TYPE;
            BEGIN
                IF NEW."label_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."label_id" IS DISTINCT FROM OLD."label_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."label_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_12_testapp_hall"
                BEFORE INSERT OR UPDATE ON "testapp_hall"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_12_testapp_hall"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_12_testapp_hall" ON "testapp_hall";

            DROP FUNCTION "soft_delete_guard_on_12_testapp_hall"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_headlinefestival" table! [SQL:fd275fb207dd]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_24_testapp_headlinefestival"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_festival"._deleted_at%TYPE;
            BEGIN
                IF NEW."sponsor_id" IS NOT NULL
                   AND (TG_OP = 'INSERT' OR NEW."sponsor_id" IS DISTINCT FROM OLD."sponsor_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."sponsor_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        UPDATE "testapp_festival" SET _deleted_at = guitars_stamp
                        WHERE "id" = NEW."touringfestival_ptr_id" AND _deleted_at IS NULL;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_24_testapp_headlinefestival"
                AFTER INSERT OR UPDATE ON "testapp_headlinefestival"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_24_testapp_headlinefestival"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_24_testapp_headlinefestival" ON "testapp_headlinefestival";

            DROP FUNCTION "soft_delete_guard_on_24_testapp_headlinefestival"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_ledger" table! [SQL:8b02f59be839]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_14_testapp_ledger"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_ledger"._deleted_at%TYPE;
            BEGIN
                IF NEW."mirror_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."mirror_id" IS DISTINCT FROM OLD."mirror_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_ledger" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."mirror_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                IF NEW."parent_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."parent_id" IS DISTINCT FROM OLD."parent_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_ledger" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."parent_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_14_testapp_ledger"
                BEFORE INSERT OR UPDATE ON "testapp_ledger"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_14_testapp_ledger"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_14_testapp_ledger" ON "testapp_ledger";

            DROP FUNCTION "soft_delete_guard_on_14_testapp_ledger"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_listing" table! [SQL:8f405764f872]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_15_testapp_listing"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_listing"._deleted_at%TYPE;
            BEGIN
                IF NEW."catalog_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."catalog_id" IS DISTINCT FROM OLD."catalog_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_catalog" AS guitars_parent
                    WHERE guitars_parent."code" = NEW."catalog_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_15_testapp_listing"
                BEFORE INSERT OR UPDATE ON "testapp_listing"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_15_testapp_listing"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_15_testapp_listing" ON "testapp_listing";

            DROP FUNCTION "soft_delete_guard_on_15_testapp_listing"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_merch" table! [SQL:1ed8b13acbd5]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_13_testapp_merch"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_merch"._deleted_at%TYPE;
            BEGIN
                IF NEW."album_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."album_id" IS DISTINCT FROM OLD."album_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_album" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."album_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                IF NEW."bonus_album_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."bonus_album_id" IS DISTINCT FROM OLD."bonus_album_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_album" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."bonus_album_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_13_testapp_merch"
                BEFORE INSERT OR UPDATE ON "testapp_merch"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_13_testapp_merch"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_13_testapp_merch" ON "testapp_merch";

            DROP FUNCTION "soft_delete_guard_on_13_testapp_merch"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_offshoot" table! [SQL:a7b5ed3abf0b]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_16_testapp_offshoot"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_lineage"._deleted_at%TYPE;
            BEGIN
                IF NEW."parent_id" IS NOT NULL
                   AND (TG_OP = 'INSERT' OR NEW."parent_id" IS DISTINCT FROM OLD."parent_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_lineage" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."parent_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        UPDATE "testapp_lineage" SET _deleted_at = guitars_stamp
                        WHERE "id" = NEW."lineage_ptr_id" AND _deleted_at IS NULL;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_16_testapp_offshoot"
                AFTER INSERT OR UPDATE ON "testapp_offshoot"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_16_testapp_offshoot"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_16_testapp_offshoot" ON "testapp_offshoot";

            DROP FUNCTION "soft_delete_guard_on_16_testapp_offshoot"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_rack" table! [SQL:414bf1bd9f05]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_12_testapp_rack"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_rack"._deleted_at%TYPE;
            BEGIN
                IF NEW."parent_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."parent_id" IS DISTINCT FROM OLD."parent_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_rack" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."parent_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_12_testapp_rack"
                BEFORE INSERT OR UPDATE ON "testapp_rack"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_12_testapp_rack"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_12_testapp_rack" ON "testapp_rack";

            DROP FUNCTION "soft_delete_guard_on_12_testapp_rack"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_relay" table! [SQL:223095002a35]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_13_testapp_relay"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_relay"._deleted_at%TYPE;
            BEGIN
                IF NEW."baton_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."baton_id" IS DISTINCT FROM OLD."baton_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_baton" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."baton_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_13_testapp_relay"
                BEFORE INSERT OR UPDATE ON "testapp_relay"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_13_testapp_relay"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_13_testapp_relay" ON "testapp_relay";

            DROP FUNCTION "soft_delete_guard_on_13_testapp_relay"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_release" table! [SQL:ac8c41e26ff9]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_15_testapp_release"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_release"._deleted_at%TYPE;
            BEGIN
                IF NEW."label_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."label_id" IS DISTINCT FROM OLD."label_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."label_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_15_testapp_release"
                BEFORE INSERT OR UPDATE ON "testapp_release"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_15_testapp_release"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_15_testapp_release" ON "testapp_release";

            DROP FUNCTION "soft_delete_guard_on_15_testapp_release"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_review" table! [SQL:59095c90d93f]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_14_testapp_review"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_review"._deleted_at%TYPE;
            BEGIN
                IF NEW."release_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."release_id" IS DISTINCT FROM OLD."release_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_release" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."release_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_14_testapp_review"
                BEFORE INSERT OR UPDATE ON "testapp_review"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_14_testapp_review"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_14_testapp_review" ON "testapp_review";

            DROP FUNCTION "soft_delete_guard_on_14_testapp_review"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_reward" table! [SQL:8ac4fca9f2e8]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_14_testapp_reward"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_reward"._deleted_at%TYPE;
            BEGIN
                IF NEW."tier_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."tier_id" IS DISTINCT FROM OLD."tier_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_tier" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."tier_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_14_testapp_reward"
                BEFORE INSERT OR UPDATE ON "testapp_reward"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_14_testapp_reward"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_14_testapp_reward" ON "testapp_reward";

            DROP FUNCTION "soft_delete_guard_on_14_testapp_reward"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_seat" table! [SQL:3687cb632d29]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_12_testapp_seat"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_seat"._deleted_at%TYPE;
            BEGIN
                IF NEW."ticket_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."ticket_id" IS DISTINCT FROM OLD."ticket_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_ticket" AS guitars_parent
                    WHERE guitars_parent."number" = NEW."ticket_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_12_testapp_seat"
                BEFORE INSERT OR UPDATE ON "testapp_seat"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_12_testapp_seat"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_12_testapp_seat" ON "testapp_seat";

            DROP FUNCTION "soft_delete_guard_on_12_testapp_seat"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_section" table! [SQL:5c19e4609b16]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_15_testapp_section"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_section"._deleted_at%TYPE;
            BEGIN
                IF NEW."orchestra_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."orchestra_id" IS DISTINCT FROM OLD."orchestra_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_ensemble" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."orchestra_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_15_testapp_section"
                BEFORE INSERT OR UPDATE ON "testapp_section"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_15_testapp_section"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_15_testapp_section" ON "testapp_section";

            DROP FUNCTION "soft_delete_guard_on_15_testapp_section"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_setlist" table! [SQL:6e38cdb4f0fe]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_15_testapp_setlist"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_setlist"._deleted_at%TYPE;
            BEGIN
                IF NEW."parent_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."parent_id" IS DISTINCT FROM OLD."parent_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_setlist" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."parent_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_15_testapp_setlist"
                BEFORE INSERT OR UPDATE ON "testapp_setlist"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_15_testapp_setlist"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_15_testapp_setlist" ON "testapp_setlist";

            DROP FUNCTION "soft_delete_guard_on_15_testapp_setlist"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_setlistentry" table! [SQL:293507f08b69]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_20_testapp_setlistentry"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_setlistentry"._deleted_at%TYPE;
            BEGIN
                IF NEW."setlist_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."setlist_id" IS DISTINCT FROM OLD."setlist_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_setlist" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."setlist_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_20_testapp_setlistentry"
                BEFORE INSERT OR UPDATE ON "testapp_setlistentry"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_20_testapp_setlistentry"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_20_testapp_setlistentry" ON "testapp_setlistentry";

            DROP FUNCTION "soft_delete_guard_on_20_testapp_setlistentry"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_tier" table! [SQL:49c1584c72b3]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_12_testapp_tier"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_tier"._deleted_at%TYPE;
            BEGIN
                IF NEW."offer_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."offer_id" IS DISTINCT FROM OLD."offer_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_offer" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."offer_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_12_testapp_tier"
                BEFORE INSERT OR UPDATE ON "testapp_tier"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_12_testapp_tier"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_12_testapp_tier" ON "testapp_tier";

            DROP FUNCTION "soft_delete_guard_on_12_testapp_tier"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_tour" table! [SQL:f27fd9ef61a4]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_12_testapp_tour"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_tour"._deleted_at%TYPE;
            BEGIN
                IF NEW."label_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."label_id" IS DISTINCT FROM OLD."label_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."label_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_12_testapp_tour"
                BEFORE INSERT OR UPDATE ON "testapp_tour"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_12_testapp_tour"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_12_testapp_tour" ON "testapp_tour";

            DROP FUNCTION "soft_delete_guard_on_12_testapp_tour"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_touringfestival" table! [SQL:b72a4dfd379b]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_23_testapp_touringfestival"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_festival"._deleted_at%TYPE;
            BEGIN
                IF NEW."promoter_id" IS NOT NULL
                   AND (TG_OP = 'INSERT' OR NEW."promoter_id" IS DISTINCT FROM OLD."promoter_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."promoter_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        UPDATE "testapp_festival" SET _deleted_at = guitars_stamp
                        WHERE "id" = NEW."festival_ptr_id" AND _deleted_at IS NULL;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_23_testapp_touringfestival"
                AFTER INSERT OR UPDATE ON "testapp_touringfestival"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_23_testapp_touringfestival"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_23_testapp_touringfestival" ON "testapp_touringfestival";

            DROP FUNCTION "soft_delete_guard_on_23_testapp_touringfestival"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_track" table! [SQL:13d7cb7b66b8]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_13_testapp_track"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_track"._deleted_at%TYPE;
            BEGIN
                IF NEW."label_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."label_id" IS DISTINCT FROM OLD."label_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."label_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                IF NEW."release_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."release_id" IS DISTINCT FROM OLD."release_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_release" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."release_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_13_testapp_track"
                BEFORE INSERT OR UPDATE ON "testapp_track"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_13_testapp_track"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_13_testapp_track" ON "testapp_track";

            DROP FUNCTION "soft_delete_guard_on_13_testapp_track"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_troupe" table! [SQL:a412d9f7ee32]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_14_testapp_troupe"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_troupe"._deleted_at%TYPE;
            BEGIN
                IF NEW."label_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."label_id" IS DISTINCT FROM OLD."label_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."label_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                IF NEW."parent_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."parent_id" IS DISTINCT FROM OLD."parent_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_troupe" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."parent_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_14_testapp_troupe"
                BEFORE INSERT OR UPDATE ON "testapp_troupe"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_14_testapp_troupe"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_14_testapp_troupe" ON "testapp_troupe";

            DROP FUNCTION "soft_delete_guard_on_14_testapp_troupe"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_venue" table! [SQL:c7fcca2c0b45]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_13_testapp_venue"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_venue"._deleted_at%TYPE;
            BEGIN
                IF NEW."label_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."label_id" IS DISTINCT FROM OLD."label_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_label" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."label_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_13_testapp_venue"
                BEFORE INSERT OR UPDATE ON "testapp_venue"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_13_testapp_venue"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_13_testapp_venue" ON "testapp_venue";

            DROP FUNCTION "soft_delete_guard_on_13_testapp_venue"();
        """,
        ),

    ]
