# Generated by makeguitarmigrations command! [DIGEST:903ed5e0a338fee3727d1fb974616a90]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0096_twig'),
    ]

    operations = [
        # Soft Delete Rule on "testapp_twig" table! [SQL:8be2bfb28827]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "testapp_twig"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "testapp_twig"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "testapp_twig";
        """,
        ),

        # Soft Delete Cascade Trigger on "testapp_twig" table! [SQL:2ae178b4890f]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_cascade_on_12_testapp_twig"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' AND EXISTS (
                    SELECT 1
                    FROM guitars_revive_after AS guitars_after
                    LEFT JOIN guitars_revive_before AS guitars_before
                        ON guitars_before."id" = guitars_after."id"
                    WHERE (guitars_before."id" IS NULL AND guitars_after._deleted_at IS NOT NULL)
                       OR (guitars_before."id" IS NOT NULL
                           AND (guitars_before._deleted_at IS NULL) <> (guitars_after._deleted_at IS NULL))
                ) THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_revive_after AS guitars_after
                        WHERE guitars_after._deleted_at IS NOT NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_revive_before AS guitars_before
                              WHERE guitars_before."id" = guitars_after."id"
                          )
                    ) AND (
                        EXISTS (
                            SELECT 1 FROM "testapp_twig" AS guitars_child
                            WHERE guitars_child._deleted_at IS NULL
                              AND (
                                  guitars_child."parent_id" IN (
                                      SELECT guitars_held."id"
                                      FROM guitars_revive_before AS guitars_held
                                      WHERE guitars_held._deleted_at IS NULL
                                  )
                                  OR guitars_child."parent_id" IN (
                                      SELECT guitars_new."id"
                                      FROM guitars_revive_after AS guitars_new
                                      WHERE guitars_new._deleted_at IS NOT NULL
                                        AND NOT EXISTS (
                                            SELECT 1 FROM guitars_revive_before AS guitars_old
                                            WHERE guitars_old."id" = guitars_new."id"
                                        )
                                  )
                              )
                        )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % archived a row whose primary key it also '
                            'rewrote, and a live child is left holding a key it read. The cascade pairs '
                            'a row across the statement on its primary key, so it cannot tell which '
                            'before-row that archived row was, and would leave the child live under an '
                            'archived parent. Rewrite the key and archive the row in separate '
                            'statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) THEN
                    UPDATE "testapp_twig" AS guitars_child
                    SET _deleted_at = guitars_archived._deleted_at
                    FROM (
                        SELECT guitars_before."id" AS guitars_key, guitars_after._deleted_at
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_child."parent_id" = guitars_archived.guitars_key
                      AND guitars_child._deleted_at IS NULL;
                    END IF;
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NOT NULL
                          AND guitars_after._deleted_at IS NULL
                    ) THEN
                    UPDATE "testapp_twig" AS guitars_child
                    SET _deleted_at = NULL
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NOT NULL
                          AND guitars_after._deleted_at IS NULL
                    ) AS guitars_revived
                    WHERE guitars_child."parent_id" = guitars_revived."id"
                      AND guitars_child._deleted_at = guitars_revived._deleted_at;
                    END IF;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_cascade_on_12_testapp_twig"
                AFTER UPDATE ON "testapp_twig"
                REFERENCING OLD TABLE AS guitars_revive_before NEW TABLE AS guitars_revive_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_cascade_on_12_testapp_twig"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_cascade_on_12_testapp_twig" ON "testapp_twig";

            DROP FUNCTION "soft_delete_cascade_on_12_testapp_twig"();
        """,
        ),

        # Soft Delete Cascade Guard on "testapp_twig" table! [SQL:8fbe81898c23]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_guard_on_12_testapp_twig"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            DECLARE
                guitars_stamp "testapp_twig"._deleted_at%TYPE;
            BEGIN
                IF NEW."parent_id" IS NOT NULL AND NEW._deleted_at IS NULL
                   AND (TG_OP = 'INSERT' OR NEW."parent_id" IS DISTINCT FROM OLD."parent_id") THEN
                    SELECT guitars_parent._deleted_at INTO guitars_stamp
                    FROM "testapp_twig" AS guitars_parent
                    WHERE guitars_parent."id" = NEW."parent_id"
                    FOR SHARE OF guitars_parent;
                    IF guitars_stamp IS NOT NULL THEN
                        NEW._deleted_at := guitars_stamp;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER "soft_delete_guard_on_12_testapp_twig"
                BEFORE INSERT OR UPDATE ON "testapp_twig"
                FOR EACH ROW
                EXECUTE FUNCTION "soft_delete_guard_on_12_testapp_twig"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_guard_on_12_testapp_twig" ON "testapp_twig";

            DROP FUNCTION "soft_delete_guard_on_12_testapp_twig"();
        """,
        ),

    ]
