# Generated by Django 5.2.18 on 2026-10-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue66_recreated', '0002_auto_enforcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Part',
        ),
    ]
