# Generated by makeguitarmigrations command! [DIGEST:c413230d312ec06e4bc91c8ca633cb36]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0082_auto_enforcement_stamp_function'),
        ('issue66_recreated', '0006_auto_enforcement'),
    ]

    operations = [
        # Updated at Trigger on "issue66_recreated_part" table! [SQL:a3c1e237980d]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "issue66_recreated_part"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "issue66_recreated_part";
        """,
        ),

        # Soft Delete Rule on "issue66_recreated_part" table! [SQL:9cc570b815f8]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "issue66_recreated_part"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "issue66_recreated_part"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "issue66_recreated_part";
        """,
        ),

    ]
