# Generated by makeguitarmigrations command! [DIGEST:d1582e2977eaa7bf5f7b6a6b120b015d]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue66_anc', '0004_forget_hub'),
    ]

    operations = [
        # Soft Delete Cascade Trigger on "issue66_shop_hub" table! [SQL:4b2b601b3a53]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS "soft_delete_cascade_on_15_issue66_anc_hub" ON "issue66_shop_hub";
            DROP FUNCTION IF EXISTS "soft_delete_cascade_on_15_issue66_anc_hub"();

            CREATE OR REPLACE FUNCTION "soft_delete_cascade_on_16_issue66_shop_hub"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' AND EXISTS (
                    SELECT 1
                    FROM guitars_revive_after AS guitars_after
                    LEFT JOIN guitars_revive_before AS guitars_before
                        ON guitars_before."id" = guitars_after."id"
                    WHERE (guitars_before."id" IS NULL AND guitars_after._deleted_at IS NOT NULL)
                       OR (guitars_before."id" IS NOT NULL
                           AND (guitars_before._deleted_at IS NULL) <> (guitars_after._deleted_at IS NULL))
                ) THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_revive_after AS guitars_after
                        WHERE guitars_after._deleted_at IS NOT NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_revive_before AS guitars_before
                              WHERE guitars_before."id" = guitars_after."id"
                          )
                    ) AND (
                        EXISTS (
                            SELECT 1 FROM "issue66_shop_spoke" AS guitars_child
                            WHERE guitars_child._deleted_at IS NULL
                              AND guitars_child."hub_id" IN (
                                  SELECT guitars_held."id"
                                  FROM guitars_revive_before AS guitars_held
                                  WHERE guitars_held._deleted_at IS NULL
                              )
                        )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % archived a row whose primary key it also '
                            'rewrote, and a live child is left holding a key it read. The cascade pairs '
                            'a row across the statement on its primary key, so it cannot tell which '
                            'before-row that archived row was, and would leave the child live under an '
                            'archived parent. Rewrite the key and archive the row in separate '
                            'statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) THEN
                    UPDATE "issue66_shop_spoke" AS guitars_child
                    SET _deleted_at = guitars_archived._deleted_at, _updated_at = NOW()
                    FROM (
                        SELECT guitars_before."id" AS guitars_key, guitars_after._deleted_at
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_child."hub_id" = guitars_archived.guitars_key
                      AND guitars_child._deleted_at IS NULL;
                    END IF;
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NOT NULL
                          AND guitars_after._deleted_at IS NULL
                    ) THEN
                    UPDATE "issue66_shop_spoke" AS guitars_child
                    SET _deleted_at = NULL, _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_revive_before AS guitars_before
                        JOIN guitars_revive_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NOT NULL
                          AND guitars_after._deleted_at IS NULL
                    ) AS guitars_revived
                    WHERE guitars_child."hub_id" = guitars_revived."id"
                      AND guitars_child._deleted_at = guitars_revived._deleted_at;
                    END IF;
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE OR REPLACE TRIGGER "soft_delete_cascade_on_16_issue66_shop_hub"
                AFTER UPDATE ON "issue66_shop_hub"
                REFERENCING OLD TABLE AS guitars_revive_before NEW TABLE AS guitars_revive_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_cascade_on_16_issue66_shop_hub"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_cascade_on_16_issue66_shop_hub" ON "issue66_shop_hub";

            DROP FUNCTION "soft_delete_cascade_on_16_issue66_shop_hub"();
        """,
        ),

    ]
