# Generated by makeguitarmigrations command! [DIGEST:ce6e2cadb1c9935a06af78e9dfe044b7]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0082_auto_enforcement_stamp_function'),
        ('issue66_anc', '0006_adopt_hub'),
    ]

    operations = [
        # Updated at Trigger on "issue66_anc_hub" table! [SQL:9ba24f17b60c]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "issue66_anc_hub"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "issue66_anc_hub";
        """,
        ),

        # Soft Delete Rule on "issue66_anc_hub" table! [SQL:14dacf0edf03]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "issue66_anc_hub"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "issue66_anc_hub"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "issue66_anc_hub";
        """,
        ),

    ]
