# Generated by makeguitarmigrations command! [DIGEST:05057da3085b8879cdf7e7a82de96bb8]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0082_auto_enforcement_stamp_function'),
        ('issue66_shop', '0004_repoint_hub'),
    ]

    operations = [
        # Updated at Trigger on "issue66_shop_hub" table! [SQL:c0f0c31f5047]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "issue66_shop_hub"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "issue66_shop_hub";
        """,
        ),

        # Soft Delete Rule on "issue66_shop_hub" table! [SQL:732d5ffae70f]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "issue66_shop_hub"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "issue66_shop_hub"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "issue66_shop_hub";
        """,
        ),

        # Soft Delete Owned Sweep on "issue66_shop_hub" that is owned by "issue66_shop_keeper" via "hub_id"! [SQL:856583c7b831]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS "soft_delete_owned_sweep_19_issue66_shop_keeper_15_is_c0b4aeafe8" ON "issue66_shop_keeper";
            DROP FUNCTION IF EXISTS "soft_delete_owned_sweep_19_issue66_shop_keeper_15_is_c0b4aeafe8"();

            DROP TRIGGER IF EXISTS "soft_delete_owned_sweep_19_issue66_shop_keeper_16_is_8843a8c0cb" ON "issue66_shop_keeper";

            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_19_issue66_shop_keeper_16_is_8843a8c0cb"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_owned_before AS guitars_before
                        JOIN "issue66_shop_hub" AS guitars_dependent
                            ON guitars_dependent."id" = guitars_before."hub_id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_before."hub_id" IS NOT NULL
                          AND guitars_dependent._deleted_at IS NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_owned_after AS guitars_after
                              WHERE guitars_after."id" = guitars_before."id"
                          )
                          AND NOT EXISTS (
                              SELECT 1 FROM "issue66_shop_keeper" AS guitars_owner
                              WHERE guitars_owner."hub_id" = guitars_before."hub_id"
                                AND guitars_owner._deleted_at IS NULL
                          )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % rewrote the primary key of a live owning row '
                            'whose dependent is now held by no live owner. The owned sweep correlates '
                            'its transition tables on the primary key, so it cannot tell whether that '
                            'row was archived, and would leak the dependent permanently. Rewrite the '
                            'key and archive the row in separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                    UPDATE "issue66_shop_hub" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_owned_before AS guitars_before
                        JOIN guitars_owned_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_before."hub_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."hub_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "issue66_shop_keeper" AS guitars_owner
                          WHERE guitars_owner."hub_id" = guitars_archived."hub_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_19_issue66_shop_keeper_16_is_8843a8c0cb"
                AFTER UPDATE ON "issue66_shop_keeper"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_19_issue66_shop_keeper_16_is_8843a8c0cb"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_19_issue66_shop_keeper_16_is_8843a8c0cb" ON "issue66_shop_keeper";

            DROP FUNCTION "soft_delete_owned_sweep_19_issue66_shop_keeper_16_is_8843a8c0cb"();
        """,
        ),

    ]
