# Generated by Django 5.2.15 on 2026-08-02 19:08

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Ancestor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    '_deleted_at',
                    models.DateTimeField(editable=False, null=True, verbose_name='Deleted at'),
                ),
                (
                    '_created_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Created at',
                    ),
                ),
                (
                    '_updated_at',
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name='Updated at',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [
                    models.Index(
                        condition=models.Q(('_deleted_at__isnull', True)),
                        fields=['_deleted_at'],
                        name='ancestor_deleted_at',
                    )
                ],
            },
        ),
    ]
