# Generated by makeguitarmigrations command! [DIGEST:04318d13f567b37641a9c6425cdee36a]

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0082_auto_enforcement_stamp_function'),
        ('mti_incremental', '0001_initial'),
    ]

    operations = [
        # Updated at Trigger on "mti_incremental_ancestor" table! [SQL:e0bcc68b8f5d]
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER updated_at_trigger
                BEFORE UPDATE ON mti_incremental_ancestor
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON mti_incremental_ancestor;
        """,
        ),
        # Soft Delete Rule on "mti_incremental_ancestor" table! [SQL:7d3064b98d37]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO mti_incremental_ancestor
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE mti_incremental_ancestor
                    SET _deleted_at = NOW()
                    WHERE id = old.id AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON mti_incremental_ancestor;
        """,
        ),
    ]
