# Generated by makeguitarmigrations command! [DIGEST:44cb69332f87a495581a64b870d3a4f7]

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0082_auto_enforcement_stamp_function'),
        ('mti_incremental', '0003_descendant'),
    ]

    operations = [
        # Updated at Trigger on "mti_incremental_ancestor" table! [SQL:6331b5096099]
        migrations.RunSQL(
            sql="""
            DROP TRIGGER updated_at_trigger ON "mti_incremental_ancestor";

            CREATE TRIGGER updated_at_trigger
                BEFORE UPDATE ON "mti_incremental_ancestor"
                FOR EACH ROW
                EXECUTE FUNCTION stamp_updated_at();
        """,
            reverse_sql="""
            DROP TRIGGER updated_at_trigger ON "mti_incremental_ancestor";
        """,
        ),
        # Soft Delete Rule on "mti_incremental_ancestor" table! [SQL:0f8e7e9dc10b]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE RULE soft_delete
                AS ON DELETE TO "mti_incremental_ancestor"
                WHERE COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on'
                DO INSTEAD (
                    UPDATE "mti_incremental_ancestor"
                    SET _deleted_at = NOW()
                    WHERE "id" = old."id" AND _deleted_at IS NULL
                );
        """,
            reverse_sql="""
            DROP RULE soft_delete ON "mti_incremental_ancestor";
        """,
        ),
    ]
