# Generated by makeguitarmigrations command! [DIGEST:ced66be8f7c9658edd1b153a7f49664a]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossapp_owner', '0001_initial'),
        ('crossapp_third', '0002_auto_enforcement'),
    ]

    operations = [
        # Soft Delete Owned Sweep on "crossapp_dependent_shared" that is owned by "crossapp_third_thirdowner" via "target_id"! [SQL:0a06a289012a]
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION "soft_delete_owned_sweep_25_crossapp_third_thirdowner_f41d94999a"()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                IF COALESCE(current_setting('rules.hard_deletion', true), '') <> 'on' THEN
                    IF EXISTS (
                        SELECT 1
                        FROM guitars_owned_before AS guitars_before
                        JOIN "crossapp_dependent_shared" AS guitars_dependent
                            ON guitars_dependent."id" = guitars_before."target_id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_before."target_id" IS NOT NULL
                          AND guitars_dependent._deleted_at IS NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM guitars_owned_after AS guitars_after
                              WHERE guitars_after."id" = guitars_before."id"
                          )
                          AND NOT EXISTS (
                              SELECT 1 FROM "crossapp_third_thirdowner" AS guitars_owner
                              WHERE guitars_owner."target_id" = guitars_before."target_id"
                                AND guitars_owner._deleted_at IS NULL
                          )
                      AND NOT EXISTS (
                          SELECT 1 FROM "crossapp_dependent_localowner" AS guitars_owner_1
                          WHERE guitars_owner_1."target_id" = guitars_before."target_id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "crossapp_owner_owner" AS guitars_owner_2
                          WHERE guitars_owner_2."target_id" = guitars_before."target_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      )
                    ) THEN
                        RAISE EXCEPTION
                            'guitars: a statement on % rewrote the primary key of a live owning row '
                            'whose dependent is now held by no live owner. The owned sweep correlates '
                            'its transition tables on the primary key, so it cannot tell whether that '
                            'row was archived, and would leak the dependent permanently. Rewrite the '
                            'key and archive the row in separate statements.', TG_TABLE_NAME
                            USING ERRCODE = 'feature_not_supported';
                    END IF;
                    UPDATE "crossapp_dependent_shared" AS guitars_dependent
                    SET _deleted_at = NOW(), _updated_at = NOW()
                    FROM (
                        SELECT guitars_before.*
                        FROM guitars_owned_before AS guitars_before
                        JOIN guitars_owned_after AS guitars_after
                            ON guitars_after."id" = guitars_before."id"
                        WHERE guitars_before._deleted_at IS NULL
                          AND guitars_after._deleted_at IS NOT NULL
                          AND guitars_before."target_id" IS NOT NULL
                    ) AS guitars_archived
                    WHERE guitars_dependent."id" = guitars_archived."target_id"
                      AND guitars_dependent._deleted_at IS NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM "crossapp_third_thirdowner" AS guitars_owner
                          WHERE guitars_owner."target_id" = guitars_archived."target_id"
                            AND guitars_owner."id" <> guitars_archived."id"
                            AND guitars_owner._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "crossapp_dependent_localowner" AS guitars_owner_1
                          WHERE guitars_owner_1."target_id" = guitars_archived."target_id"
                            AND guitars_owner_1._deleted_at IS NULL
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM "crossapp_owner_owner" AS guitars_owner_2
                          WHERE guitars_owner_2."target_id" = guitars_archived."target_id"
                            AND guitars_owner_2._deleted_at IS NULL
                      );
                END IF;
                RETURN NULL;
            END;
            $$;

            CREATE TRIGGER "soft_delete_owned_sweep_25_crossapp_third_thirdowner_f41d94999a"
                AFTER UPDATE ON "crossapp_third_thirdowner"
                REFERENCING OLD TABLE AS guitars_owned_before NEW TABLE AS guitars_owned_after
                FOR EACH STATEMENT
                EXECUTE FUNCTION "soft_delete_owned_sweep_25_crossapp_third_thirdowner_f41d94999a"();
        """,
            reverse_sql="""
            DROP TRIGGER "soft_delete_owned_sweep_25_crossapp_third_thirdowner_f41d94999a" ON "crossapp_third_thirdowner";

            DROP FUNCTION "soft_delete_owned_sweep_25_crossapp_third_thirdowner_f41d94999a"();
        """,
        ),

    ]
